        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 07 10:20:30 2007
        MODULE SKIN_FRICTION_mod
          INTERFACE 
            FUNCTION SKIN_FRICTION(FTYPE,FFACTOR,DEPTH,UVEL,VVEL,NU)    &
     & RESULT(SKIN_FRICTION_0)
              INTEGER(KIND=4), INTENT(IN) :: FTYPE
              REAL(KIND=8), INTENT(IN) :: FFACTOR
              REAL(KIND=8), INTENT(IN) :: DEPTH
              REAL(KIND=8), INTENT(IN) :: UVEL
              REAL(KIND=8), INTENT(IN) :: VVEL
              REAL(KIND=8), INTENT(IN) :: NU
              REAL(KIND=8) :: SKIN_FRICTION_0
            END FUNCTION SKIN_FRICTION
          END INTERFACE 
        END MODULE SKIN_FRICTION_mod
