        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:33 2017
        MODULE ADD_ARRAY_PTOH__genmod
          INTERFACE 
            SUBROUTINE ADD_ARRAY_PTOH(I,N,IARRAY)
              INTEGER(KIND=4), INTENT(INOUT) :: N
              INTEGER(KIND=4), INTENT(IN) :: I
              INTEGER(KIND=4), INTENT(INOUT) :: IARRAY(N+1)
            END SUBROUTINE ADD_ARRAY_PTOH
          END INTERFACE 
        END MODULE ADD_ARRAY_PTOH__genmod
