        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:33 2017
        MODULE ADJUST_BED_ELEVATION__genmod
          INTERFACE 
            SUBROUTINE ADJUST_BED_ELEVATION(ZCHANGE)
              LOGICAL(KIND=4), INTENT(OUT) :: ZCHANGE
            END SUBROUTINE ADJUST_BED_ELEVATION
          END INTERFACE 
        END MODULE ADJUST_BED_ELEVATION__genmod
