        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:33 2017
        MODULE ADJUST_WATER_DEPTH__genmod
          INTERFACE 
            SUBROUTINE ADJUST_WATER_DEPTH
            END SUBROUTINE ADJUST_WATER_DEPTH
          END INTERFACE 
        END MODULE ADJUST_WATER_DEPTH__genmod
