        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE AZIMUTH2ANGLE__genmod
          INTERFACE 
            FUNCTION AZIMUTH2ANGLE(X)
              REAL(KIND=8), INTENT(IN) :: X
              REAL(KIND=8) :: AZIMUTH2ANGLE
            END FUNCTION AZIMUTH2ANGLE
          END INTERFACE 
        END MODULE AZIMUTH2ANGLE__genmod
