        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE BED_SLOPE_ETA__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_ETA(SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE BED_SLOPE_ETA
          END INTERFACE 
        END MODULE BED_SLOPE_ETA__genmod
