        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:40 2017
        MODULE BED_SLOPE_VTX__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_VTX
            END SUBROUTINE BED_SLOPE_VTX
          END INTERFACE 
        END MODULE BED_SLOPE_VTX__genmod
