        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE BED_SLOPE_STD__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_STD
            END SUBROUTINE BED_SLOPE_STD
          END INTERFACE 
        END MODULE BED_SLOPE_STD__genmod
