        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:20 2017
        MODULE BYEBYE__genmod
          INTERFACE 
            SUBROUTINE BYEBYE(ERROR_MSG)
              CHARACTER(*), INTENT(IN) :: ERROR_MSG
            END SUBROUTINE BYEBYE
          END INTERFACE 
        END MODULE BYEBYE__genmod
