        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE C2V_SETUP__genmod
          INTERFACE 
            SUBROUTINE C2V_SETUP(TYPE)
              INTEGER(KIND=4), INTENT(IN) :: TYPE
            END SUBROUTINE C2V_SETUP
          END INTERFACE 
        END MODULE C2V_SETUP__genmod
