        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:39:46 2017
        MODULE CELL_CENTERED__genmod
          INTERFACE 
            FUNCTION CELL_CENTERED(VAR,STRING)
              CHARACTER(*), INTENT(IN) :: VAR
              CHARACTER(*), INTENT(IN) :: STRING
              LOGICAL(KIND=4) :: CELL_CENTERED
            END FUNCTION CELL_CENTERED
          END INTERFACE 
        END MODULE CELL_CENTERED__genmod
