        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE CHAN_ARRAYS__genmod
          INTERFACE 
            SUBROUTINE CHAN_ARRAYS
            END SUBROUTINE CHAN_ARRAYS
          END INTERFACE 
        END MODULE CHAN_ARRAYS__genmod
