        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:33 2017
        MODULE CRIT_OUTFLOW__genmod
          INTERFACE 
            SUBROUTINE CRIT_OUTFLOW
            END SUBROUTINE CRIT_OUTFLOW
          END INTERFACE 
        END MODULE CRIT_OUTFLOW__genmod
