        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE CVDISCH__genmod
          INTERFACE 
            SUBROUTINE CVDISCH
            END SUBROUTINE CVDISCH
          END INTERFACE 
        END MODULE CVDISCH__genmod
