        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:18 2017
        MODULE DELTAT__genmod
          INTERFACE 
            FUNCTION DELTAT(CRTYPE,CFL)
              INTEGER(KIND=4), INTENT(IN) :: CRTYPE
              REAL(KIND=8), INTENT(IN) :: CFL
              REAL(KIND=8) :: DELTAT
            END FUNCTION DELTAT
          END INTERFACE 
        END MODULE DELTAT__genmod
