        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE DIRICHLET__genmod
          INTERFACE 
            SUBROUTINE DIRICHLET(I,RKSTEP)
              INTEGER(KIND=4), INTENT(IN) :: I
              INTEGER(KIND=4), INTENT(IN) :: RKSTEP
            END SUBROUTINE DIRICHLET
          END INTERFACE 
        END MODULE DIRICHLET__genmod
