        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE EDDY_VISCOSITY__genmod
          INTERFACE 
            SUBROUTINE EDDY_VISCOSITY
            END SUBROUTINE EDDY_VISCOSITY
          END INTERFACE 
        END MODULE EDDY_VISCOSITY__genmod
