        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:32 2017
        MODULE ELEMNT_DB__genmod
          INTERFACE 
            SUBROUTINE ELEMNT_DB
            END SUBROUTINE ELEMNT_DB
          END INTERFACE 
        END MODULE ELEMNT_DB__genmod
