        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:39:52 2017
        MODULE ERR_OPTS__genmod
          INTERFACE 
            SUBROUTINE ERR_OPTS(STRING,LINENO)
              CHARACTER(*) :: STRING
              INTEGER(KIND=4), INTENT(IN) :: LINENO
            END SUBROUTINE ERR_OPTS
          END INTERFACE 
        END MODULE ERR_OPTS__genmod
