        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:39:49 2017
        MODULE FINDTTCHECK__genmod
          INTERFACE 
            FUNCTION FINDTTCHECK(STRG)
              CHARACTER(*), INTENT(IN) :: STRG
              LOGICAL(KIND=4) :: FINDTTCHECK
            END FUNCTION FINDTTCHECK
          END INTERFACE 
        END MODULE FINDTTCHECK__genmod
