        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:42 2017
        MODULE FIND_EDGES__genmod
          INTERFACE 
            SUBROUTINE FIND_EDGES
            END SUBROUTINE FIND_EDGES
          END INTERFACE 
        END MODULE FIND_EDGES__genmod
