        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:29 2017
        MODULE FIND_DRY_CELLS__genmod
          INTERFACE 
            SUBROUTINE FIND_DRY_CELLS
            END SUBROUTINE FIND_DRY_CELLS
          END INTERFACE 
        END MODULE FIND_DRY_CELLS__genmod
