        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE FRIC_TERMS_IMPL__genmod
          INTERFACE 
            SUBROUTINE FRIC_TERMS_IMPL(DELTA_T)
              REAL(KIND=8), INTENT(IN) :: DELTA_T
            END SUBROUTINE FRIC_TERMS_IMPL
          END INTERFACE 
        END MODULE FRIC_TERMS_IMPL__genmod
