        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE GAUSSGRAD__genmod
          INTERFACE 
            SUBROUTINE GAUSSGRAD(PHI,GRADPHI,NDIM)
              USE PARAMETERS
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              REAL(KIND=8), INTENT(IN) :: PHI(NDIM)
              TYPE (VECTOR), INTENT(OUT) :: GRADPHI(NDIM)
            END SUBROUTINE GAUSSGRAD
          END INTERFACE 
        END MODULE GAUSSGRAD__genmod
