        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE GAUSSGRAD_SETUP__genmod
          INTERFACE 
            SUBROUTINE GAUSSGRAD_SETUP
            END SUBROUTINE GAUSSGRAD_SETUP
          END INTERFACE 
        END MODULE GAUSSGRAD_SETUP__genmod
