        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:39:51 2017
        MODULE GET_EXTENSION__genmod
          INTERFACE 
            FUNCTION GET_EXTENSION(FNAME)
              CHARACTER(*), INTENT(IN) :: FNAME
              CHARACTER(LEN=3) :: GET_EXTENSION
            END FUNCTION GET_EXTENSION
          END INTERFACE 
        END MODULE GET_EXTENSION__genmod
