        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:09 2017
        MODULE GET_TIME_BCS__genmod
          INTERFACE 
            SUBROUTINE GET_TIME_BCS(TIME)
              REAL(KIND=8), INTENT(IN) :: TIME
            END SUBROUTINE GET_TIME_BCS
          END INTERFACE 
        END MODULE GET_TIME_BCS__genmod
