        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:39:47 2017
        MODULE GET_IOUNIT__genmod
          INTERFACE 
            FUNCTION GET_IOUNIT(IOUNIT)
              INTEGER(KIND=4), INTENT(OUT) :: IOUNIT
              LOGICAL(KIND=4) :: GET_IOUNIT
            END FUNCTION GET_IOUNIT
          END INTERFACE 
        END MODULE GET_IOUNIT__genmod
