        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE HDLSQ_GRAD_ARRAY4H__genmod
          INTERFACE 
            SUBROUTINE HDLSQ_GRAD_ARRAY4H
            END SUBROUTINE HDLSQ_GRAD_ARRAY4H
          END INTERFACE 
        END MODULE HDLSQ_GRAD_ARRAY4H__genmod
