        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE HDLSQ_SETUP__genmod
          INTERFACE 
            SUBROUTINE HDLSQ_SETUP(WTYPE)
              INTEGER(KIND=4), INTENT(IN) :: WTYPE
            END SUBROUTINE HDLSQ_SETUP
          END INTERFACE 
        END MODULE HDLSQ_SETUP__genmod
