        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:29 2017
        MODULE HEADER__genmod
          INTERFACE 
            SUBROUTINE HEADER(ID,FILENAME,TITLE)
              INTEGER(KIND=4), INTENT(IN) :: ID
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE HEADER
          END INTERFACE 
        END MODULE HEADER__genmod
