        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE HEFFECTIVE__genmod
          INTERFACE 
            FUNCTION HEFFECTIVE(CELL_NO)
              INTEGER(KIND=4), INTENT(IN) :: CELL_NO
              REAL(KIND=8) :: HEFFECTIVE
            END FUNCTION HEFFECTIVE
          END INTERFACE 
        END MODULE HEFFECTIVE__genmod
