        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE HGRADFIX2__genmod
          INTERFACE 
            SUBROUTINE HGRADFIX2(RKSTEP,SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: RKSTEP
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE HGRADFIX2
          END INTERFACE 
        END MODULE HGRADFIX2__genmod
