        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:23 2017
        MODULE HOT_START_ASCII__genmod
          INTERFACE 
            SUBROUTINE HOT_START_ASCII
            END SUBROUTINE HOT_START_ASCII
          END INTERFACE 
        END MODULE HOT_START_ASCII__genmod
