        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:37 2017
        MODULE IBC_ARRAYS__genmod
          INTERFACE 
            SUBROUTINE IBC_ARRAYS
            END SUBROUTINE IBC_ARRAYS
          END INTERFACE 
        END MODULE IBC_ARRAYS__genmod
