        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:30 2017
        MODULE INITIALIZE_OPTIONS__genmod
          INTERFACE 
            SUBROUTINE INITIALIZE_OPTIONS
            END SUBROUTINE INITIALIZE_OPTIONS
          END INTERFACE 
        END MODULE INITIALIZE_OPTIONS__genmod
