        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:28 2017
        MODULE INVERT_EDGE_DIRS__genmod
          INTERFACE 
            FUNCTION INVERT_EDGE_DIRS(E)
              USE PARAMETERS
              TYPE (EDGE), INTENT(INOUT) :: E
              REAL(KIND=8) :: INVERT_EDGE_DIRS
            END FUNCTION INVERT_EDGE_DIRS
          END INTERFACE 
        END MODULE INVERT_EDGE_DIRS__genmod
