        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE INVISC_FLUXES__genmod
          INTERFACE 
            SUBROUTINE INVISC_FLUXES
            END SUBROUTINE INVISC_FLUXES
          END INTERFACE 
        END MODULE INVISC_FLUXES__genmod
