        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:46 2017
        MODULE IOFLOW__genmod
          INTERFACE 
            SUBROUTINE IOFLOW(FUNIT)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
            END SUBROUTINE IOFLOW
          END INTERFACE 
        END MODULE IOFLOW__genmod
