        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE LIMITERBJ__genmod
          INTERFACE 
            SUBROUTINE LIMITERBJ(BETA,Q,GRADQ,NDIM)
              USE PARAMETERS
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              REAL(KIND=8), INTENT(IN) :: BETA
              REAL(KIND=8), INTENT(IN) :: Q(NDIM)
              TYPE (VECTOR), INTENT(INOUT) :: GRADQ(NDIM)
            END SUBROUTINE LIMITERBJ
          END INTERFACE 
        END MODULE LIMITERBJ__genmod
