        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE LSQ_GRAD_ARRAY4H__genmod
          INTERFACE 
            SUBROUTINE LSQ_GRAD_ARRAY4H(SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE LSQ_GRAD_ARRAY4H
          END INTERFACE 
        END MODULE LSQ_GRAD_ARRAY4H__genmod
