        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE LSQ_GRADIENT__genmod
          INTERFACE 
            SUBROUTINE LSQ_GRADIENT(SOLVER,NODE,PHI,NDIM,PHIX,PHIY)
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
              INTEGER(KIND=4), INTENT(IN) :: NODE
              REAL(KIND=8), INTENT(IN) :: PHI(NDIM)
              REAL(KIND=8), INTENT(OUT) :: PHIX
              REAL(KIND=8), INTENT(OUT) :: PHIY
            END SUBROUTINE LSQ_GRADIENT
          END INTERFACE 
        END MODULE LSQ_GRADIENT__genmod
