        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE LSQ_GRAD_ARRAY__genmod
          INTERFACE 
            SUBROUTINE LSQ_GRAD_ARRAY(SOLVER,PHI,GRADPHI,NDIM)
              USE PARAMETERS
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
              REAL(KIND=8), INTENT(IN) :: PHI(NDIM)
              TYPE (VECTOR), INTENT(OUT) :: GRADPHI(NDIM)
            END SUBROUTINE LSQ_GRAD_ARRAY
          END INTERFACE 
        END MODULE LSQ_GRAD_ARRAY__genmod
