        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE MARGINS__genmod
          INTERFACE 
            SUBROUTINE MARGINS
            END SUBROUTINE MARGINS
          END INTERFACE 
        END MODULE MARGINS__genmod
