        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:23 2017
        MODULE NEIGHBOR__genmod
          INTERFACE 
            FUNCTION NEIGHBOR(ELEMNT,EDG)
              INTEGER(KIND=4), INTENT(IN) :: ELEMNT
              INTEGER(KIND=4), INTENT(IN) :: EDG
              INTEGER(KIND=4) :: NEIGHBOR
            END FUNCTION NEIGHBOR
          END INTERFACE 
        END MODULE NEIGHBOR__genmod
