        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:23 2017
        MODULE NODE_DB__genmod
          INTERFACE 
            SUBROUTINE NODE_DB
              USE GEOMETRY
            END SUBROUTINE NODE_DB
          END INTERFACE 
        END MODULE NODE_DB__genmod
