        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:42 2017
        MODULE NODE_IN_TRIANG__genmod
          INTERFACE 
            FUNCTION NODE_IN_TRIANG(N,T)
              USE PARAMETERS
              INTEGER(KIND=4), INTENT(IN) :: N
              TYPE (TRIANGLE), INTENT(IN) :: T
              LOGICAL(KIND=4) :: NODE_IN_TRIANG
            END FUNCTION NODE_IN_TRIANG
          END INTERFACE 
        END MODULE NODE_IN_TRIANG__genmod
