        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE POSITIVITY_VTX__genmod
          INTERFACE 
            SUBROUTINE POSITIVITY_VTX
            END SUBROUTINE POSITIVITY_VTX
          END INTERFACE 
        END MODULE POSITIVITY_VTX__genmod
