        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:45 2017
        MODULE PROBEFILEH__genmod
          INTERFACE 
            FUNCTION PROBEFILEH
              INTEGER(KIND=4) :: PROBEFILEH
            END FUNCTION PROBEFILEH
          END INTERFACE 
        END MODULE PROBEFILEH__genmod
