        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:22 2017
        MODULE READ_OPTIONS__genmod
          INTERFACE 
            SUBROUTINE READ_OPTIONS(FUNIT)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
            END SUBROUTINE READ_OPTIONS
          END INTERFACE 
        END MODULE READ_OPTIONS__genmod
