        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:24 2017
        MODULE READ_DATA__genmod
          INTERFACE 
            SUBROUTINE READ_DATA(FILENAME,TITLE)
              CHARACTER(*), INTENT(OUT) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_DATA
          END INTERFACE 
        END MODULE READ_DATA__genmod
