        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:22 2017
        MODULE READ_MFA__genmod
          INTERFACE 
            SUBROUTINE READ_MFA(FILENAME,TITLE)
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_MFA
          END INTERFACE 
        END MODULE READ_MFA__genmod
