        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE READLINE__genmod
          INTERFACE 
            FUNCTION READLINE(FUNIT,LINE,LINENO)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
              CHARACTER(LEN=40), INTENT(OUT) :: LINE
              INTEGER(KIND=4), INTENT(INOUT) :: LINENO
              LOGICAL(KIND=4) :: READLINE
            END FUNCTION READLINE
          END INTERFACE 
        END MODULE READLINE__genmod
