        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:26 2017
        MODULE READ_CGNS__genmod
          INTERFACE 
            SUBROUTINE READ_CGNS(FILENAME,TITLE)
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_CGNS
          END INTERFACE 
        END MODULE READ_CGNS__genmod
