        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:44 2017
        MODULE RVEGDATA__genmod
          INTERFACE 
            SUBROUTINE RVEGDATA
            END SUBROUTINE RVEGDATA
          END INTERFACE 
        END MODULE RVEGDATA__genmod
