        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:19 2017
        MODULE SORTEDGES__genmod
          INTERFACE 
            FUNCTION SORTEDGES(N,IARRAY)
              INTEGER(KIND=4), INTENT(IN) :: N
              INTEGER(KIND=4), INTENT(INOUT) :: IARRAY(N)
              LOGICAL(KIND=4) :: SORTEDGES
            END FUNCTION SORTEDGES
          END INTERFACE 
        END MODULE SORTEDGES__genmod
