        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:24 2017
        MODULE TECPLOT_READ__genmod
          INTERFACE 
            SUBROUTINE TECPLOT_READ(ID,VARLOC)
              INTEGER(KIND=4), INTENT(IN) :: ID
              CHARACTER(*), INTENT(IN) :: VARLOC
            END SUBROUTINE TECPLOT_READ
          END INTERFACE 
        END MODULE TECPLOT_READ__genmod
