        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:34 2017
        MODULE TECPLOT_WRITE__genmod
          INTERFACE 
            SUBROUTINE TECPLOT_WRITE(ID)
              INTEGER(KIND=4), INTENT(IN) :: ID
            END SUBROUTINE TECPLOT_WRITE
          END INTERFACE 
        END MODULE TECPLOT_WRITE__genmod
