        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:16 2017
        MODULE TO_VERTICES__genmod
          INTERFACE 
            SUBROUTINE TO_VERTICES
            END SUBROUTINE TO_VERTICES
          END INTERFACE 
        END MODULE TO_VERTICES__genmod
