        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE VISC_FLUXES__genmod
          INTERFACE 
            SUBROUTINE VISC_FLUXES
            END SUBROUTINE VISC_FLUXES
          END INTERFACE 
        END MODULE VISC_FLUXES__genmod
