        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:40:30 2017
        MODULE VTX2CTR__genmod
          INTERFACE 
            SUBROUTINE VTX2CTR(VARRAY,CARRAY)
              USE GEOMETRY
              REAL(KIND=8), INTENT(IN) :: VARRAY(N_PTS)
              REAL(KIND=8), INTENT(OUT) :: CARRAY(N_ELEMS)
            END SUBROUTINE VTX2CTR
          END INTERFACE 
        END MODULE VTX2CTR__genmod
