        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE WENSLP2_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WENSLP2_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP2_FLUXES
          END INTERFACE 
        END MODULE WENSLP2_FLUXES__genmod
