        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE WENSLP3_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WENSLP3_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP3_FLUXES
          END INTERFACE 
        END MODULE WENSLP3_FLUXES__genmod
