        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE WENSLP_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WENSLP_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP_FLUXES
          END INTERFACE 
        END MODULE WENSLP_FLUXES__genmod
