        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE WESLP2_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WESLP2_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP2_FLUXES
          END INTERFACE 
        END MODULE WESLP2_FLUXES__genmod
