        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:26 2017
        MODULE WESLP3_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WESLP3_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP3_FLUXES
          END INTERFACE 
        END MODULE WESLP3_FLUXES__genmod
