        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:35 2017
        MODULE WESLP_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WESLP_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP_FLUXES
          END INTERFACE 
        END MODULE WESLP_FLUXES__genmod
