        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:58 2017
        MODULE WRITE_CGNS__genmod
          INTERFACE 
            SUBROUTINE WRITE_CGNS(TTIME)
              REAL(KIND=8), INTENT(IN) :: TTIME
            END SUBROUTINE WRITE_CGNS
          END INTERFACE 
        END MODULE WRITE_CGNS__genmod
