        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 02 13:48:24 2017
        MODULE WRITE_CGNS_CELL__genmod
          INTERFACE 
            SUBROUTINE WRITE_CGNS_CELL(TTIME)
              REAL(KIND=8), INTENT(IN) :: TTIME
            END SUBROUTINE WRITE_CGNS_CELL
          END INTERFACE 
        END MODULE WRITE_CGNS_CELL__genmod
