        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 01 12:41:34 2017
        MODULE ZETA_BCS__genmod
          INTERFACE 
            SUBROUTINE ZETA_BCS
            END SUBROUTINE ZETA_BCS
          END INTERFACE 
        END MODULE ZETA_BCS__genmod
