        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 21 10:28:20 2014
        MODULE FINDTTCHECK__genmod
          INTERFACE 
            FUNCTION FINDTTCHECK(STRG)
              CHARACTER(*), INTENT(IN) :: STRG
              LOGICAL(KIND=4) :: FINDTTCHECK
            END FUNCTION FINDTTCHECK
          END INTERFACE 
        END MODULE FINDTTCHECK__genmod
