        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:13 2014
        MODULE ADD_ARRAY_PTOH__genmod
          INTERFACE 
            SUBROUTINE ADD_ARRAY_PTOH(I,N,IARRAY)
              INTEGER(KIND=4), INTENT(INOUT) :: N
              INTEGER(KIND=4), INTENT(IN) :: I
              INTEGER(KIND=4), INTENT(INOUT) :: IARRAY(N+1)
            END SUBROUTINE ADD_ARRAY_PTOH
          END INTERFACE 
        END MODULE ADD_ARRAY_PTOH__genmod
