        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:47:16 2009
        MODULE ADD_EDGE_TO_ARRAY_mod
          INTERFACE 
            SUBROUTINE ADD_EDGE_TO_ARRAY(EDG,EDGES_ARRAY,N)
            INTEGER(KIND=4), INTENT(INOUT) :: N
            TYPE (EDGE), INTENT(IN) :: EDG
            TYPE (EDGE), INTENT(INOUT) :: EDGES_ARRAY(N+1)
          END SUBROUTINE ADD_EDGE_TO_ARRAY
        END INTERFACE 
      END MODULE ADD_EDGE_TO_ARRAY_mod
