        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:33 2014
        MODULE ADJUST_WATER_DEPTH__genmod
          INTERFACE 
            SUBROUTINE ADJUST_WATER_DEPTH
            END SUBROUTINE ADJUST_WATER_DEPTH
          END INTERFACE 
        END MODULE ADJUST_WATER_DEPTH__genmod
