        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:45:22 2009
        MODULE ADJUST_WATER_DEPTH_mod
          INTERFACE 
            SUBROUTINE ADJUST_WATER_DEPTH
            END SUBROUTINE ADJUST_WATER_DEPTH
          END INTERFACE 
        END MODULE ADJUST_WATER_DEPTH_mod
