        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:45:22 2009
        MODULE ADJUST_BED_ELEVATION_mod
          INTERFACE 
            SUBROUTINE ADJUST_BED_ELEVATION(ZCHANGE)
              LOGICAL(KIND=4), INTENT(OUT) :: ZCHANGE
            END SUBROUTINE ADJUST_BED_ELEVATION
          END INTERFACE 
        END MODULE ADJUST_BED_ELEVATION_mod
