        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:24 2009
        MODULE ADJUSTZB_mod
          INTERFACE 
            SUBROUTINE ADJUSTZB(FLAG,E,GRADZB,GRADZB2)
            LOGICAL(KIND=4), INTENT(IN) :: FLAG
            INTEGER(KIND=4), INTENT(IN) :: E
            TYPE (VECTOR), INTENT(OUT) :: GRADZB
            TYPE (VECTOR), INTENT(OUT) :: GRADZB2
          END SUBROUTINE ADJUSTZB
        END INTERFACE 
      END MODULE ADJUSTZB_mod
