        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:53 2009
        MODULE AFE_FLUX_mod
          INTERFACE 
            SUBROUTINE AFE_FLUX
            END SUBROUTINE AFE_FLUX
          END INTERFACE 
        END MODULE AFE_FLUX_mod
