        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:49 2009
        MODULE ALLOC_ERR_mod
          INTERFACE 
            SUBROUTINE ALLOC_ERR(I)
              INTEGER(KIND=4), INTENT(IN) :: I
            END SUBROUTINE ALLOC_ERR
          END INTERFACE 
        END MODULE ALLOC_ERR_mod
