        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:43 2014
        MODULE AZIMUTH2ANGLE__genmod
          INTERFACE 
            FUNCTION AZIMUTH2ANGLE(X)
              REAL(KIND=8), INTENT(IN) :: X
              REAL(KIND=8) :: AZIMUTH2ANGLE
            END FUNCTION AZIMUTH2ANGLE
          END INTERFACE 
        END MODULE AZIMUTH2ANGLE__genmod
