        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:57 2014
        MODULE BED_SLOPE_ETA__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_ETA(SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE BED_SLOPE_ETA
          END INTERFACE 
        END MODULE BED_SLOPE_ETA__genmod
