        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:40:06 2014
        MODULE BED_SLOPE_DFB__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_DFB
            END SUBROUTINE BED_SLOPE_DFB
          END INTERFACE 
        END MODULE BED_SLOPE_DFB__genmod
