        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:28 2014
        MODULE BED_SLOPE__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE
            END SUBROUTINE BED_SLOPE
          END INTERFACE 
        END MODULE BED_SLOPE__genmod
