        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:19 2009
        MODULE BED_SLOPE_STD_mod
          INTERFACE 
            SUBROUTINE BED_SLOPE_STD
            END SUBROUTINE BED_SLOPE_STD
          END INTERFACE 
        END MODULE BED_SLOPE_STD_mod
