        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:51 2014
        MODULE BED_SLOPE_STD__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_STD
            END SUBROUTINE BED_SLOPE_STD
          END INTERFACE 
        END MODULE BED_SLOPE_STD__genmod
