        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:57 2009
        MODULE BED_SLOPE_ETA_mod
          INTERFACE 
            SUBROUTINE BED_SLOPE_ETA(SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE BED_SLOPE_ETA
          END INTERFACE 
        END MODULE BED_SLOPE_ETA_mod
