        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:05 2009
        MODULE BED_SLOPE_mod
          INTERFACE 
            SUBROUTINE BED_SLOPE
            END SUBROUTINE BED_SLOPE
          END INTERFACE 
        END MODULE BED_SLOPE_mod
