        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:41 2014
        MODULE BED_SLOPE_VTX__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_VTX
            END SUBROUTINE BED_SLOPE_VTX
          END INTERFACE 
        END MODULE BED_SLOPE_VTX__genmod
