        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:47 2009
        MODULE BED_SLOPE_VTX_mod
          INTERFACE 
            SUBROUTINE BED_SLOPE_VTX
            END SUBROUTINE BED_SLOPE_VTX
          END INTERFACE 
        END MODULE BED_SLOPE_VTX_mod
