        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:09 2009
        MODULE BYEBYE_mod
          INTERFACE 
            SUBROUTINE BYEBYE(ERROR_MSG)
              CHARACTER(*), INTENT(IN) :: ERROR_MSG
            END SUBROUTINE BYEBYE
          END INTERFACE 
        END MODULE BYEBYE_mod
