        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 12 11:26:32 2009
        MODULE C2V_SETUP_mod
          INTERFACE 
            SUBROUTINE C2V_SETUP(TYPE)
              INTEGER(KIND=4), INTENT(IN) :: TYPE
            END SUBROUTINE C2V_SETUP
          END INTERFACE 
        END MODULE C2V_SETUP_mod
