        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:26 2014
        MODULE C2V_SETUP__genmod
          INTERFACE 
            SUBROUTINE C2V_SETUP(TYPE)
              INTEGER(KIND=4), INTENT(IN) :: TYPE
            END SUBROUTINE C2V_SETUP
          END INTERFACE 
        END MODULE C2V_SETUP__genmod
