        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:47 2009
        MODULE CCSTRING_mod
          INTERFACE 
            FUNCTION CCSTRING(A,N,STRING) RESULT(CCSTRING_0)
              INTEGER(KIND=4), INTENT(IN) :: N
              LOGICAL(KIND=4), INTENT(IN) :: A(N)
              CHARACTER(*), INTENT(OUT) :: STRING
              INTEGER(KIND=4) :: CCSTRING_0
            END FUNCTION CCSTRING
          END INTERFACE 
        END MODULE CCSTRING_mod
