        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:15 2014
        MODULE CELL_CENTERED__genmod
          INTERFACE 
            FUNCTION CELL_CENTERED(VAR,STRING)
              CHARACTER(*), INTENT(IN) :: VAR
              CHARACTER(*), INTENT(IN) :: STRING
              LOGICAL(KIND=4) :: CELL_CENTERED
            END FUNCTION CELL_CENTERED
          END INTERFACE 
        END MODULE CELL_CENTERED__genmod
