        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:46 2009
        MODULE CELL_CENTERED_mod
          INTERFACE 
            FUNCTION CELL_CENTERED(VAR,STRING) RESULT(CELL_CENTERED_0)
              CHARACTER(*), INTENT(IN) :: VAR
              CHARACTER(*), INTENT(IN) :: STRING
              LOGICAL(KIND=4) :: CELL_CENTERED_0
            END FUNCTION CELL_CENTERED
          END INTERFACE 
        END MODULE CELL_CENTERED_mod
