        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:40:00 2014
        MODULE CHAN_ARRAYS__genmod
          INTERFACE 
            SUBROUTINE CHAN_ARRAYS
            END SUBROUTINE CHAN_ARRAYS
          END INTERFACE 
        END MODULE CHAN_ARRAYS__genmod
