        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:43 2014
        MODULE CORRECT_VTX__genmod
          INTERFACE 
            SUBROUTINE CORRECT_VTX(DEPTH,WSELEV,WETV,N)
              INTEGER(KIND=4), INTENT(IN) :: N
              REAL(KIND=8), INTENT(OUT) :: DEPTH(N)
              REAL(KIND=8), INTENT(OUT) :: WSELEV(N)
              LOGICAL(KIND=4), INTENT(OUT) :: WETV(N)
            END SUBROUTINE CORRECT_VTX
          END INTERFACE 
        END MODULE CORRECT_VTX__genmod
