        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:36 2014
        MODULE CRIT_OUTFLOW__genmod
          INTERFACE 
            SUBROUTINE CRIT_OUTFLOW
            END SUBROUTINE CRIT_OUTFLOW
          END INTERFACE 
        END MODULE CRIT_OUTFLOW__genmod
