        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:26 2009
        MODULE CRIT_OUTFLOW_mod
          INTERFACE 
            SUBROUTINE CRIT_OUTFLOW
            END SUBROUTINE CRIT_OUTFLOW
          END INTERFACE 
        END MODULE CRIT_OUTFLOW_mod
