        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:56 2009
        MODULE CTR2VTX_mod
          INTERFACE 
            SUBROUTINE CTR2VTX(TYPE,CARRAY,VARRAY)
            INTEGER(KIND=4), INTENT(IN) :: TYPE
            REAL(KIND=8), INTENT(IN) :: CARRAY(N_ELEMS)
            REAL(KIND=8), INTENT(OUT) :: VARRAY(N_PTS)
          END SUBROUTINE CTR2VTX
        END INTERFACE 
      END MODULE CTR2VTX_mod
