        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:56 2014
        MODULE CTR2VTX__genmod
          INTERFACE 
            SUBROUTINE CTR2VTX(TYPE,CARRAY,VARRAY)
              USE GEOMETRY
              INTEGER(KIND=4), INTENT(IN) :: TYPE
              REAL(KIND=8), INTENT(IN) :: CARRAY(N_ELEMS)
              REAL(KIND=8), INTENT(OUT) :: VARRAY(N_PTS)
            END SUBROUTINE CTR2VTX
          END INTERFACE 
        END MODULE CTR2VTX__genmod
