        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:41 2014
        MODULE CVDISCH__genmod
          INTERFACE 
            SUBROUTINE CVDISCH
            END SUBROUTINE CVDISCH
          END INTERFACE 
        END MODULE CVDISCH__genmod
