        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:30 2009
        MODULE DELTATFVT_mod
          INTERFACE 
            FUNCTION DELTATFVT(CRTYPE,CFL) RESULT(DELTATFVT_0)
              INTEGER(KIND=4), INTENT(IN) :: CRTYPE
              REAL(KIND=8), INTENT(IN) :: CFL
              REAL(KIND=8) :: DELTATFVT_0
            END FUNCTION DELTATFVT
          END INTERFACE 
        END MODULE DELTATFVT_mod
