        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:08 2009
        MODULE DELTAT_mod
          INTERFACE 
            FUNCTION DELTAT(CRTYPE,CFL) RESULT(DELTAT_0)
              INTEGER(KIND=4), INTENT(IN) :: CRTYPE
              REAL(KIND=8), INTENT(IN) :: CFL
              REAL(KIND=8) :: DELTAT_0
            END FUNCTION DELTAT
          END INTERFACE 
        END MODULE DELTAT_mod
