        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:31 2014
        MODULE DIRICHLET__genmod
          INTERFACE 
            SUBROUTINE DIRICHLET(I,RKSTEP)
              INTEGER(KIND=4), INTENT(IN) :: I
              INTEGER(KIND=4), INTENT(IN) :: RKSTEP
            END SUBROUTINE DIRICHLET
          END INTERFACE 
        END MODULE DIRICHLET__genmod
