        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:53 2014
        MODULE DISTRIBUTION__genmod
          INTERFACE 
            FUNCTION DISTRIBUTION
              INTEGER(KIND=4) :: DISTRIBUTION
            END FUNCTION DISTRIBUTION
          END INTERFACE 
        END MODULE DISTRIBUTION__genmod
