        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:02 2009
        MODULE DISTRIBUTION_mod
          INTERFACE 
            FUNCTION DISTRIBUTION RESULT(DISTRIBUTION_0)
              INTEGER(KIND=4) :: DISTRIBUTION_0
            END FUNCTION DISTRIBUTION
          END INTERFACE 
        END MODULE DISTRIBUTION_mod
