        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:38 2014
        MODULE DRYNWET__genmod
          INTERFACE 
            SUBROUTINE DRYNWET(E,ZOUT)
              USE PARAMETERS
              TYPE (TRIANGLE), INTENT(IN) :: E
              REAL(KIND=8), INTENT(OUT) :: ZOUT(3)
            END SUBROUTINE DRYNWET
          END INTERFACE 
        END MODULE DRYNWET__genmod
