        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:23 2009
        MODULE DRYNWET_mod
          INTERFACE 
            SUBROUTINE DRYNWET(E,ZOUT)
            TYPE (TRIANGLE), INTENT(IN) :: E
            REAL(KIND=8), INTENT(OUT) :: ZOUT(3)
          END SUBROUTINE DRYNWET
        END INTERFACE 
      END MODULE DRYNWET_mod
