        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:53 2009
        MODULE EDDY_VISCOSITY_mod
          INTERFACE 
            SUBROUTINE EDDY_VISCOSITY
            END SUBROUTINE EDDY_VISCOSITY
          END INTERFACE 
        END MODULE EDDY_VISCOSITY_mod
