        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:28 2014
        MODULE EDDY_VISCOSITY__genmod
          INTERFACE 
            SUBROUTINE EDDY_VISCOSITY
            END SUBROUTINE EDDY_VISCOSITY
          END INTERFACE 
        END MODULE EDDY_VISCOSITY__genmod
