        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:22 2014
        MODULE EDGE_COPY__genmod
          INTERFACE 
            SUBROUTINE EDGE_COPY(IN_EDGE,OUT_EDGE)
              USE PARAMETERS
              TYPE (EDGE), INTENT(IN) :: IN_EDGE
              TYPE (EDGE), INTENT(OUT) :: OUT_EDGE
            END SUBROUTINE EDGE_COPY
          END INTERFACE 
        END MODULE EDGE_COPY__genmod
