        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:47:17 2009
        MODULE EDGE_NORMALS_mod
          INTERFACE 
            SUBROUTINE EDGE_NORMALS(SIDE,NSIDE,PTO,NPTO)
            INTEGER(KIND=4), INTENT(IN) :: NPTO
            INTEGER(KIND=4), INTENT(IN) :: NSIDE
            TYPE (EDGE) :: SIDE(NSIDE)
            TYPE (POINT) :: PTO(NPTO)
          END SUBROUTINE EDGE_NORMALS
        END INTERFACE 
      END MODULE EDGE_NORMALS_mod
