        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:45:37 2009
        MODULE EDGE_IN_ELEMENT_mod
          INTERFACE 
            FUNCTION EDGE_IN_ELEMENT(E) RESULT(EDGE_IN_ELEMENT_0)
            TYPE (EDGE), INTENT(IN) :: E
            INTEGER(KIND=4) :: EDGE_IN_ELEMENT_0
          END FUNCTION EDGE_IN_ELEMENT
        END INTERFACE 
      END MODULE EDGE_IN_ELEMENT_mod
