        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:48:00 2009
        MODULE EDGE_COPY_mod
          INTERFACE 
            SUBROUTINE EDGE_COPY(IN_EDGE,OUT_EDGE)
            TYPE (EDGE), INTENT(IN) :: IN_EDGE
            TYPE (EDGE), INTENT(OUT) :: OUT_EDGE
          END SUBROUTINE EDGE_COPY
        END INTERFACE 
      END MODULE EDGE_COPY_mod
