        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:45:35 2009
        MODULE EDGE_IN_ARRAY_mod
          INTERFACE 
            FUNCTION EDGE_IN_ARRAY(EDG,EDGES_ARRAY,N) RESULT(           &
     &EDGE_IN_ARRAY_0)
            INTEGER(KIND=4), INTENT(IN) :: N
            TYPE (EDGE), INTENT(IN) :: EDG
            TYPE (EDGE), INTENT(IN) :: EDGES_ARRAY(N+1)
            LOGICAL(KIND=4) :: EDGE_IN_ARRAY_0
          END FUNCTION EDGE_IN_ARRAY
        END INTERFACE 
      END MODULE EDGE_IN_ARRAY_mod
