        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:42 2014
        MODULE EDGE_IN_ELEMENT__genmod
          INTERFACE 
            FUNCTION EDGE_IN_ELEMENT(E)
              USE PARAMETERS
              TYPE (EDGE), INTENT(IN) :: E
              INTEGER(KIND=4) :: EDGE_IN_ELEMENT
            END FUNCTION EDGE_IN_ELEMENT
          END INTERFACE 
        END MODULE EDGE_IN_ELEMENT__genmod
