        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:56 2009
        MODULE ELEMNT_DB_mod
          INTERFACE 
            SUBROUTINE ELEMNT_DB
            END SUBROUTINE ELEMNT_DB
          END INTERFACE 
        END MODULE ELEMNT_DB_mod
