        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:25 2014
        MODULE ENFORCE_BCS__genmod
          INTERFACE 
            SUBROUTINE ENFORCE_BCS(H0,U0,V0,Z0,NDIM)
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              REAL(KIND=8), INTENT(INOUT) :: H0(NDIM)
              REAL(KIND=8), INTENT(INOUT) :: U0(NDIM)
              REAL(KIND=8), INTENT(INOUT) :: V0(NDIM)
              REAL(KIND=8), INTENT(INOUT) :: Z0(NDIM)
            END SUBROUTINE ENFORCE_BCS
          END INTERFACE 
        END MODULE ENFORCE_BCS__genmod
