        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:18 2009
        MODULE ENFORCE_BCS_mod
          INTERFACE 
            SUBROUTINE ENFORCE_BCS(H0,U0,V0,Z0,NDIM)
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              REAL(KIND=8), INTENT(INOUT) :: H0(NDIM)
              REAL(KIND=8), INTENT(INOUT) :: U0(NDIM)
              REAL(KIND=8), INTENT(INOUT) :: V0(NDIM)
              REAL(KIND=8), INTENT(INOUT) :: Z0(NDIM)
            END SUBROUTINE ENFORCE_BCS
          END INTERFACE 
        END MODULE ENFORCE_BCS_mod
