        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:48:03 2009
        MODULE EQUALS_mod
          INTERFACE 
            FUNCTION EQUALS(A,B) RESULT(EQUALS_0)
              REAL(KIND=8), INTENT(IN) :: A
              REAL(KIND=8), INTENT(IN) :: B
              LOGICAL(KIND=4) :: EQUALS_0
            END FUNCTION EQUALS
          END INTERFACE 
        END MODULE EQUALS_mod
