        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:46 2009
        MODULE ERR_OPTS_mod
          INTERFACE 
            SUBROUTINE ERR_OPTS(STRING,LINENO)
              CHARACTER(*) :: STRING
              INTEGER(KIND=4), INTENT(IN) :: LINENO
            END SUBROUTINE ERR_OPTS
          END INTERFACE 
        END MODULE ERR_OPTS_mod
