        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:14 2014
        MODULE ERR_OPTS__genmod
          INTERFACE 
            SUBROUTINE ERR_OPTS(STRING,LINENO)
              CHARACTER(*) :: STRING
              INTEGER(KIND=4), INTENT(IN) :: LINENO
            END SUBROUTINE ERR_OPTS
          END INTERFACE 
        END MODULE ERR_OPTS__genmod
