        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:31 2014
        MODULE ERROR_EST__genmod
          INTERFACE 
            SUBROUTINE ERROR_EST(ETYPE)
              INTEGER(KIND=4) :: ETYPE
            END SUBROUTINE ERROR_EST
          END INTERFACE 
        END MODULE ERROR_EST__genmod
