        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:32 2009
        MODULE ERRORE_mod
          INTERFACE 
            SUBROUTINE ERRORE
            END SUBROUTINE ERRORE
          END INTERFACE 
        END MODULE ERRORE_mod
