        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:11 2009
        MODULE ERROR_EST_mod
          INTERFACE 
            SUBROUTINE ERROR_EST(ETYPE)
              INTEGER(KIND=4) :: ETYPE
            END SUBROUTINE ERROR_EST
          END INTERFACE 
        END MODULE ERROR_EST_mod
