        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:53 2014
        MODULE FIND_DRY_CELLS__genmod
          INTERFACE 
            SUBROUTINE FIND_DRY_CELLS
            END SUBROUTINE FIND_DRY_CELLS
          END INTERFACE 
        END MODULE FIND_DRY_CELLS__genmod
