        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:23 2009
        MODULE FIND_DRY_CELLS_mod
          INTERFACE 
            SUBROUTINE FIND_DRY_CELLS
            END SUBROUTINE FIND_DRY_CELLS
          END INTERFACE 
        END MODULE FIND_DRY_CELLS_mod
