        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:38 2014
        MODULE FIND_EDGES__genmod
          INTERFACE 
            SUBROUTINE FIND_EDGES
            END SUBROUTINE FIND_EDGES
          END INTERFACE 
        END MODULE FIND_EDGES__genmod
