        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:14 2014
        MODULE FINDTTCHECK__genmod
          INTERFACE 
            FUNCTION FINDTTCHECK(STRG)
              CHARACTER(*), INTENT(IN) :: STRG
              LOGICAL(KIND=4) :: FINDTTCHECK
            END FUNCTION FINDTTCHECK
          END INTERFACE 
        END MODULE FINDTTCHECK__genmod
