        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:52 2009
        MODULE FIND_EDGES_mod
          INTERFACE 
            SUBROUTINE FIND_EDGES
            END SUBROUTINE FIND_EDGES
          END INTERFACE 
        END MODULE FIND_EDGES_mod
