        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:47:17 2009
        MODULE FLUX_RUSANOV_mod
          INTERFACE 
            SUBROUTINE FLUX_RUSANOV(CELLEDGE,HLEFT,ULEFT,VLEFT,         &
     &SQRTGHLEFT,HRIGHT,URIGHT,VRIGHT,SQRTGHRIGHT,FLUX)
            TYPE (EDGE), INTENT(IN) :: CELLEDGE
            REAL(KIND=8), INTENT(IN) :: HLEFT
            REAL(KIND=8), INTENT(IN) :: ULEFT
            REAL(KIND=8), INTENT(IN) :: VLEFT
            REAL(KIND=8), INTENT(IN) :: SQRTGHLEFT
            REAL(KIND=8), INTENT(IN) :: HRIGHT
            REAL(KIND=8), INTENT(IN) :: URIGHT
            REAL(KIND=8), INTENT(IN) :: VRIGHT
            REAL(KIND=8), INTENT(IN) :: SQRTGHRIGHT
            REAL(KIND=8), INTENT(OUT) :: FLUX(3)
          END SUBROUTINE FLUX_RUSANOV
        END INTERFACE 
      END MODULE FLUX_RUSANOV_mod
