        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:40:04 2014
        MODULE FLUX_RUSANOV__genmod
          INTERFACE 
            SUBROUTINE FLUX_RUSANOV(CELLEDGE,HLEFT,ULEFT,VLEFT,         &
     &SQRTGHLEFT,HRIGHT,URIGHT,VRIGHT,SQRTGHRIGHT,FLUX)
              USE PARAMETERS
              TYPE (EDGE), INTENT(IN) :: CELLEDGE
              REAL(KIND=8), INTENT(IN) :: HLEFT
              REAL(KIND=8), INTENT(IN) :: ULEFT
              REAL(KIND=8), INTENT(IN) :: VLEFT
              REAL(KIND=8), INTENT(IN) :: SQRTGHLEFT
              REAL(KIND=8), INTENT(IN) :: HRIGHT
              REAL(KIND=8), INTENT(IN) :: URIGHT
              REAL(KIND=8), INTENT(IN) :: VRIGHT
              REAL(KIND=8), INTENT(IN) :: SQRTGHRIGHT
              REAL(KIND=8), INTENT(OUT) :: FLUX(3)
            END SUBROUTINE FLUX_RUSANOV
          END INTERFACE 
        END MODULE FLUX_RUSANOV__genmod
