        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 12 15:44:55 2009
        MODULE FLUX_AC_mod
          INTERFACE 
            SUBROUTINE FLUX_AC(CELLEDGE,HLEFTY,ULEFT,VLEFT,HRIGHTY,     &
     &URIGHT,VRIGHT,FLUX)
            TYPE (EDGE), INTENT(IN) :: CELLEDGE
            REAL(KIND=8), INTENT(IN) :: HLEFTY
            REAL(KIND=8), INTENT(IN) :: ULEFT
            REAL(KIND=8), INTENT(IN) :: VLEFT
            REAL(KIND=8), INTENT(IN) :: HRIGHTY
            REAL(KIND=8), INTENT(IN) :: URIGHT
            REAL(KIND=8), INTENT(IN) :: VRIGHT
            REAL(KIND=8), INTENT(OUT) :: FLUX(3)
          END SUBROUTINE FLUX_AC
        END INTERFACE 
      END MODULE FLUX_AC_mod
