        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:45:37 2009
        MODULE FLUX_HLL_mod
          INTERFACE 
            SUBROUTINE FLUX_HLL(CELLEDGE,HLEFT,ULEFT,VLEFT,HRIGHT,URIGHT&
     &,VRIGHT,H0,FLUX)
            TYPE (EDGE), INTENT(IN) :: CELLEDGE
            REAL(KIND=8), INTENT(IN) :: HLEFT
            REAL(KIND=8), INTENT(IN) :: ULEFT
            REAL(KIND=8), INTENT(IN) :: VLEFT
            REAL(KIND=8), INTENT(IN) :: HRIGHT
            REAL(KIND=8), INTENT(IN) :: URIGHT
            REAL(KIND=8), INTENT(IN) :: VRIGHT
            REAL(KIND=8), INTENT(IN) :: H0
            REAL(KIND=8), INTENT(OUT) :: FLUX(3)
          END SUBROUTINE FLUX_HLL
        END INTERFACE 
      END MODULE FLUX_HLL_mod
