        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:40 2014
        MODULE FLUX_AC__genmod
          INTERFACE 
            SUBROUTINE FLUX_AC(CELLEDGE,HLEFTY,ULEFT,VLEFT,HRIGHTY,     &
     &URIGHT,VRIGHT,FLUX)
              USE PARAMETERS
              TYPE (EDGE), INTENT(IN) :: CELLEDGE
              REAL(KIND=8), INTENT(IN) :: HLEFTY
              REAL(KIND=8), INTENT(IN) :: ULEFT
              REAL(KIND=8), INTENT(IN) :: VLEFT
              REAL(KIND=8), INTENT(IN) :: HRIGHTY
              REAL(KIND=8), INTENT(IN) :: URIGHT
              REAL(KIND=8), INTENT(IN) :: VRIGHT
              REAL(KIND=8), INTENT(OUT) :: FLUX(3)
            END SUBROUTINE FLUX_AC
          END INTERFACE 
        END MODULE FLUX_AC__genmod
