        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:44 2009
        MODULE FNAMES_mod
          INTERFACE 
            FUNCTION FNAMES(FUNIT,FNAME) RESULT(FNAMES_0)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
              CHARACTER(LEN=80), INTENT(OUT) :: FNAME
              LOGICAL(KIND=4) :: FNAMES_0
            END FUNCTION FNAMES
          END INTERFACE 
        END MODULE FNAMES_mod
