        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:13 2014
        MODULE FNAMES__genmod
          INTERFACE 
            FUNCTION FNAMES(FUNIT,FNAME)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
              CHARACTER(LEN=80), INTENT(OUT) :: FNAME
              LOGICAL(KIND=4) :: FNAMES
            END FUNCTION FNAMES
          END INTERFACE 
        END MODULE FNAMES__genmod
