        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:00 2009
        MODULE FRIC_SLOPE_mod
          INTERFACE 
            SUBROUTINE FRIC_SLOPE
            END SUBROUTINE FRIC_SLOPE
          END INTERFACE 
        END MODULE FRIC_SLOPE_mod
