        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:37 2014
        MODULE FRIC_SLOPE__genmod
          INTERFACE 
            SUBROUTINE FRIC_SLOPE
            END SUBROUTINE FRIC_SLOPE
          END INTERFACE 
        END MODULE FRIC_SLOPE__genmod
