        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:30 2014
        MODULE FRIC_TERMS__genmod
          INTERFACE 
            SUBROUTINE FRIC_TERMS
            END SUBROUTINE FRIC_TERMS
          END INTERFACE 
        END MODULE FRIC_TERMS__genmod
