        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:21 2009
        MODULE FRIC_TERMS_mod
          INTERFACE 
            SUBROUTINE FRIC_TERMS
            END SUBROUTINE FRIC_TERMS
          END INTERFACE 
        END MODULE FRIC_TERMS_mod
