        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:20 2014
        MODULE FRIC_TERMS_IMPL__genmod
          INTERFACE 
            SUBROUTINE FRIC_TERMS_IMPL(DELTA_T)
              REAL(KIND=8), INTENT(IN) :: DELTA_T
            END SUBROUTINE FRIC_TERMS_IMPL
          END INTERFACE 
        END MODULE FRIC_TERMS_IMPL__genmod
