        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:27 2014
        MODULE GET_TIME_BCS__genmod
          INTERFACE 
            SUBROUTINE GET_TIME_BCS(TIME)
              REAL(KIND=8), INTENT(IN) :: TIME
            END SUBROUTINE GET_TIME_BCS
          END INTERFACE 
        END MODULE GET_TIME_BCS__genmod
