        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:12 2014
        MODULE GET_EXTENSION__genmod
          INTERFACE 
            FUNCTION GET_EXTENSION(FNAME)
              CHARACTER(*), INTENT(IN) :: FNAME
              CHARACTER(LEN=3) :: GET_EXTENSION
            END FUNCTION GET_EXTENSION
          END INTERFACE 
        END MODULE GET_EXTENSION__genmod
