        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:23 2009
        MODULE GET_TIME_BCS_mod
          INTERFACE 
            SUBROUTINE GET_TIME_BCS(TIME,INF1,INF2,OUTF)
              REAL(KIND=8), INTENT(IN) :: TIME
              REAL(KIND=8), INTENT(OUT) :: INF1
              REAL(KIND=8), INTENT(OUT) :: INF2
              REAL(KIND=8), INTENT(OUT) :: OUTF
            END SUBROUTINE GET_TIME_BCS
          END INTERFACE 
        END MODULE GET_TIME_BCS_mod
