        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:45 2009
        MODULE GET_EXTENSION_mod
          INTERFACE 
            FUNCTION GET_EXTENSION(FNAME) RESULT(GET_EXTENSION_0)
              CHARACTER(*), INTENT(IN) :: FNAME
              CHARACTER(LEN=3) :: GET_EXTENSION_0
            END FUNCTION GET_EXTENSION
          END INTERFACE 
        END MODULE GET_EXTENSION_mod
