        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:48 2009
        MODULE GET_IOUNIT_mod
          INTERFACE 
            FUNCTION GET_IOUNIT(UNIT) RESULT(GET_IOUNIT_0)
              INTEGER(KIND=4), INTENT(OUT) :: UNIT
              LOGICAL(KIND=4) :: GET_IOUNIT_0
            END FUNCTION GET_IOUNIT
          END INTERFACE 
        END MODULE GET_IOUNIT_mod
