        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:52 2009
        MODULE GRAD_mod
          INTERFACE 
            SUBROUTINE GRAD(PHI,NVDIM,GRADPHI,NEDIM)
              INTEGER(KIND=4), INTENT(IN) :: NEDIM
              INTEGER(KIND=4), INTENT(IN) :: NVDIM
              REAL(KIND=8), INTENT(IN) :: PHI(NVDIM)
              REAL(KIND=8), INTENT(OUT) :: GRADPHI(NEDIM,2)
            END SUBROUTINE GRAD
          END INTERFACE 
        END MODULE GRAD_mod
