        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:14 2009
        MODULE GRADHORDR_mod
          INTERFACE 
            SUBROUTINE GRADHORDR(FEGRAD,GRADPHI)
            REAL(KIND=8), INTENT(IN) :: FEGRAD(N_ELEMS,2)
            REAL(KIND=8), INTENT(OUT) :: GRADPHI(N_ELEMS,2)
          END SUBROUTINE GRADHORDR
        END INTERFACE 
      END MODULE GRADHORDR_mod
