        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:40 2014
        MODULE GRADHORDR__genmod
          INTERFACE 
            SUBROUTINE GRADHORDR(FEGRAD,GRADPHI)
              USE GEOMETRY
              REAL(KIND=8), INTENT(IN) :: FEGRAD(N_ELEMS,2)
              REAL(KIND=8), INTENT(OUT) :: GRADPHI(N_ELEMS,2)
            END SUBROUTINE GRADHORDR
          END INTERFACE 
        END MODULE GRADHORDR__genmod
