        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:40:02 2014
        MODULE HDLSQ_SETUP__genmod
          INTERFACE 
            SUBROUTINE HDLSQ_SETUP(WTYPE)
              INTEGER(KIND=4), INTENT(IN) :: WTYPE
            END SUBROUTINE HDLSQ_SETUP
          END INTERFACE 
        END MODULE HDLSQ_SETUP__genmod
