        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:24 2014
        MODULE HDLSQ_GRAD_ARRAY4H__genmod
          INTERFACE 
            SUBROUTINE HDLSQ_GRAD_ARRAY4H
            END SUBROUTINE HDLSQ_GRAD_ARRAY4H
          END INTERFACE 
        END MODULE HDLSQ_GRAD_ARRAY4H__genmod
