        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:46 2009
        MODULE HDLSQ_GRAD_ARRAY4H_mod
          INTERFACE 
            SUBROUTINE HDLSQ_GRAD_ARRAY4H
            END SUBROUTINE HDLSQ_GRAD_ARRAY4H
          END INTERFACE 
        END MODULE HDLSQ_GRAD_ARRAY4H_mod
