        !COMPILER-GENERATED INTERFACE MODULE: Tue May 13 16:19:11 2014
        MODULE HEADER__genmod
          INTERFACE 
            SUBROUTINE HEADER(ID,FILENAME,TITLE)
              INTEGER(KIND=4), INTENT(IN) :: ID
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE HEADER
          END INTERFACE 
        END MODULE HEADER__genmod
