        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:29 2009
        MODULE HEADER_mod
          INTERFACE 
            SUBROUTINE HEADER(ID,FILENAME,TITLE)
              INTEGER(KIND=4), INTENT(IN) :: ID
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE HEADER
          END INTERFACE 
        END MODULE HEADER_mod
