        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:30 2014
        MODULE HEFFECTIVE__genmod
          INTERFACE 
            FUNCTION HEFFECTIVE(CELL_NO)
              INTEGER(KIND=4), INTENT(IN) :: CELL_NO
              REAL(KIND=8) :: HEFFECTIVE
            END FUNCTION HEFFECTIVE
          END INTERFACE 
        END MODULE HEFFECTIVE__genmod
