        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:59 2009
        MODULE HEFFECTIVE_mod
          INTERFACE 
            FUNCTION HEFFECTIVE(CELL_NO) RESULT(HEFFECTIVE_0)
              INTEGER(KIND=4), INTENT(IN) :: CELL_NO
              REAL(KIND=8) :: HEFFECTIVE_0
            END FUNCTION HEFFECTIVE
          END INTERFACE 
        END MODULE HEFFECTIVE_mod
