        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 12 11:26:35 2009
        MODULE HEQUIVALENT_mod
          INTERFACE 
            SUBROUTINE HEQUIVALENT(E,HLEFT,HRIGHT)
            TYPE (EDGE), INTENT(IN) :: E
            REAL(KIND=8), INTENT(INOUT) :: HLEFT
            REAL(KIND=8), INTENT(INOUT) :: HRIGHT
          END SUBROUTINE HEQUIVALENT
        END INTERFACE 
      END MODULE HEQUIVALENT_mod
