        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:19 2014
        MODULE HEQUIVALENT__genmod
          INTERFACE 
            SUBROUTINE HEQUIVALENT(E,HLEFT,HRIGHT)
              USE PARAMETERS
              TYPE (EDGE), INTENT(IN) :: E
              REAL(KIND=8), INTENT(INOUT) :: HLEFT
              REAL(KIND=8), INTENT(INOUT) :: HRIGHT
            END SUBROUTINE HEQUIVALENT
          END INTERFACE 
        END MODULE HEQUIVALENT__genmod
