        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:52 2014
        MODULE HGRADFIX2__genmod
          INTERFACE 
            SUBROUTINE HGRADFIX2(RKSTEP,SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: RKSTEP
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE HGRADFIX2
          END INTERFACE 
        END MODULE HGRADFIX2__genmod
