        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:18 2014
        MODULE HOT_START_ASCII__genmod
          INTERFACE 
            SUBROUTINE HOT_START_ASCII
            END SUBROUTINE HOT_START_ASCII
          END INTERFACE 
        END MODULE HOT_START_ASCII__genmod
