        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:10 2009
        MODULE IBC_ARRAYS_mod
          INTERFACE 
            SUBROUTINE IBC_ARRAYS
            END SUBROUTINE IBC_ARRAYS
          END INTERFACE 
        END MODULE IBC_ARRAYS_mod
