        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:27 2014
        MODULE IBC_ARRAYS__genmod
          INTERFACE 
            SUBROUTINE IBC_ARRAYS
            END SUBROUTINE IBC_ARRAYS
          END INTERFACE 
        END MODULE IBC_ARRAYS__genmod
