        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:49 2009
        MODULE IFNAME_mod
          INTERFACE 
            SUBROUTINE IFNAME(V,VMAX,FN,FNOUT)
              INTEGER(KIND=4), INTENT(IN) :: V
              INTEGER(KIND=4), INTENT(IN) :: VMAX
              CHARACTER(*), INTENT(IN) :: FN
              CHARACTER(*), INTENT(OUT) :: FNOUT
            END SUBROUTINE IFNAME
          END INTERFACE 
        END MODULE IFNAME_mod
