        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 12 11:26:34 2009
        MODULE INFLOWQBYH_mod
          INTERFACE 
            SUBROUTINE INFLOWQBYH
            END SUBROUTINE INFLOWQBYH
          END INTERFACE 
        END MODULE INFLOWQBYH_mod
