        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:26 2009
        MODULE INFLOWQBYH2_mod
          INTERFACE 
            SUBROUTINE INFLOWQBYH2
            END SUBROUTINE INFLOWQBYH2
          END INTERFACE 
        END MODULE INFLOWQBYH2_mod
