        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:48:06 2009
        MODULE INITIALIZE_OPTIONS_mod
          INTERFACE 
            SUBROUTINE INITIALIZE_OPTIONS
            END SUBROUTINE INITIALIZE_OPTIONS
          END INTERFACE 
        END MODULE INITIALIZE_OPTIONS_mod
