        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:54 2014
        MODULE INITIALIZE_OPTIONS__genmod
          INTERFACE 
            SUBROUTINE INITIALIZE_OPTIONS
            END SUBROUTINE INITIALIZE_OPTIONS
          END INTERFACE 
        END MODULE INITIALIZE_OPTIONS__genmod
