        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:17 2009
        MODULE INTEGRAL_MD_mod
          INTERFACE 
            FUNCTION INTEGRAL_MD(NODE,PHI,NDIM) RESULT(INTEGRAL_MD_0)
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              INTEGER(KIND=4), INTENT(IN) :: NODE
              REAL(KIND=8), INTENT(IN) :: PHI(NDIM)
              REAL(KIND=8) :: INTEGRAL_MD_0
            END FUNCTION INTEGRAL_MD
          END INTERFACE 
        END MODULE INTEGRAL_MD_mod
