        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:46 2009
        MODULE INTEGRAL_UT_mod
          INTERFACE 
            FUNCTION INTEGRAL_UT(NODE,PHI,NDIM) RESULT(INTEGRAL_UT_0)
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              INTEGER(KIND=4), INTENT(IN) :: NODE
              REAL(KIND=8), INTENT(IN) :: PHI(NDIM)
              REAL(KIND=8) :: INTEGRAL_UT_0
            END FUNCTION INTEGRAL_UT
          END INTERFACE 
        END MODULE INTEGRAL_UT_mod
