        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:35 2014
        MODULE INVERT_EDGE_DIRS__genmod
          INTERFACE 
            FUNCTION INVERT_EDGE_DIRS(E)
              USE PARAMETERS
              TYPE (EDGE), INTENT(INOUT) :: E
              REAL(KIND=8) :: INVERT_EDGE_DIRS
            END FUNCTION INVERT_EDGE_DIRS
          END INTERFACE 
        END MODULE INVERT_EDGE_DIRS__genmod
