        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:45:39 2009
        MODULE INVERT_EDGE_DIRS_mod
          INTERFACE 
            FUNCTION INVERT_EDGE_DIRS(E) RESULT(INVERT_EDGE_DIRS_0)
            TYPE (EDGE), INTENT(INOUT) :: E
            REAL(KIND=8) :: INVERT_EDGE_DIRS_0
          END FUNCTION INVERT_EDGE_DIRS
        END INTERFACE 
      END MODULE INVERT_EDGE_DIRS_mod
