        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 12 15:44:54 2009
        MODULE INVISC_FLUXES_mod
          INTERFACE 
            SUBROUTINE INVISC_FLUXES
            END SUBROUTINE INVISC_FLUXES
          END INTERFACE 
        END MODULE INVISC_FLUXES_mod
