        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:59 2014
        MODULE INVISC_FLUXES__genmod
          INTERFACE 
            SUBROUTINE INVISC_FLUXES
            END SUBROUTINE INVISC_FLUXES
          END INTERFACE 
        END MODULE INVISC_FLUXES__genmod
