        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:48 2009
        MODULE IOFLOW_mod
          INTERFACE 
            SUBROUTINE IOFLOW(FUNIT)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
            END SUBROUTINE IOFLOW
          END INTERFACE 
        END MODULE IOFLOW_mod
