        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:52 2009
        MODULE IS_EDGE_mod
          INTERFACE 
            FUNCTION IS_EDGE(P1,P2) RESULT(IS_EDGE_0)
              INTEGER(KIND=4), INTENT(IN) :: P1
              INTEGER(KIND=4), INTENT(IN) :: P2
              INTEGER(KIND=4) :: IS_EDGE_0
            END FUNCTION IS_EDGE
          END INTERFACE 
        END MODULE IS_EDGE_mod
