        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:04 2009
        MODULE KINEMWAVE_SETUP_mod
          INTERFACE 
            SUBROUTINE KINEMWAVE_SETUP
            END SUBROUTINE KINEMWAVE_SETUP
          END INTERFACE 
        END MODULE KINEMWAVE_SETUP_mod
