        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:44 2009
        MODULE KINEMATICWAVE2D_mod
          INTERFACE 
            SUBROUTINE KINEMATICWAVE2D(E)
              INTEGER(KIND=4), INTENT(IN) :: E
            END SUBROUTINE KINEMATICWAVE2D
          END INTERFACE 
        END MODULE KINEMATICWAVE2D_mod
