        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:16 2009
        MODULE LIMITERBJ_mod
          INTERFACE 
            SUBROUTINE LIMITERBJ(BETA,Q,GRADQ,NDIM)
            INTEGER(KIND=4), INTENT(IN) :: NDIM
            REAL(KIND=8), INTENT(IN) :: BETA
            REAL(KIND=8), INTENT(IN) :: Q(NDIM)
            TYPE (VECTOR), INTENT(INOUT) :: GRADQ(NDIM)
          END SUBROUTINE LIMITERBJ
        END INTERFACE 
      END MODULE LIMITERBJ_mod
