        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:45:43 2009
        MODULE LOCAL_EDGE_mod
          INTERFACE 
            FUNCTION LOCAL_EDGE(ELEMENT,EDG) RESULT(LOCAL_EDGE_0)
            TYPE (TRIANGLE), INTENT(IN) :: ELEMENT
            INTEGER(KIND=4), INTENT(IN) :: EDG
            INTEGER(KIND=4) :: LOCAL_EDGE_0
          END FUNCTION LOCAL_EDGE
        END INTERFACE 
      END MODULE LOCAL_EDGE_mod
