        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:01 2009
        MODULE LSQ_SETUP_mod
          INTERFACE 
            SUBROUTINE LSQ_SETUP(SOLVER,TYPE)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
              INTEGER(KIND=4), INTENT(IN) :: TYPE
            END SUBROUTINE LSQ_SETUP
          END INTERFACE 
        END MODULE LSQ_SETUP_mod
