        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:45 2014
        MODULE LSQ_GRAD_ARRAY4H__genmod
          INTERFACE 
            SUBROUTINE LSQ_GRAD_ARRAY4H(SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE LSQ_GRAD_ARRAY4H
          END INTERFACE 
        END MODULE LSQ_GRAD_ARRAY4H__genmod
