        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:32 2009
        MODULE LSQ_GRADIENT_mod
          INTERFACE 
            SUBROUTINE LSQ_GRADIENT(SOLVER,NODE,PHI,NDIM,PHIX,PHIY)
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
              INTEGER(KIND=4), INTENT(IN) :: NODE
              REAL(KIND=8), INTENT(IN) :: PHI(NDIM)
              REAL(KIND=8), INTENT(OUT) :: PHIX
              REAL(KIND=8), INTENT(OUT) :: PHIY
            END SUBROUTINE LSQ_GRADIENT
          END INTERFACE 
        END MODULE LSQ_GRADIENT_mod
