        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:29 2009
        MODULE LSQ_GRAD_ARRAY4H_mod
          INTERFACE 
            SUBROUTINE LSQ_GRAD_ARRAY4H(SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE LSQ_GRAD_ARRAY4H
          END INTERFACE 
        END MODULE LSQ_GRAD_ARRAY4H_mod
