        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:07 2009
        MODULE LSQ_GRAD_ARRAY_mod
          INTERFACE 
            SUBROUTINE LSQ_GRAD_ARRAY(SOLVER,PHI,GRADPHI,NDIM)
            INTEGER(KIND=4), INTENT(IN) :: NDIM
            INTEGER(KIND=4), INTENT(IN) :: SOLVER
            REAL(KIND=8), INTENT(IN) :: PHI(NDIM)
            TYPE (VECTOR), INTENT(OUT) :: GRADPHI(NDIM)
          END SUBROUTINE LSQ_GRAD_ARRAY
        END INTERFACE 
      END MODULE LSQ_GRAD_ARRAY_mod
