        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:52 2014
        MODULE MARGINS__genmod
          INTERFACE 
            SUBROUTINE MARGINS
            END SUBROUTINE MARGINS
          END INTERFACE 
        END MODULE MARGINS__genmod
