        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:47:36 2009
        MODULE MEM_CALL_mod
          INTERFACE 
            FUNCTION MEM_CALL RESULT(MEM_CALL_0)
              INTEGER(KIND=4) :: MEM_CALL_0
            END FUNCTION MEM_CALL
          END INTERFACE 
        END MODULE MEM_CALL_mod
