        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:25 2009
        MODULE NARROW_mod
          INTERFACE 
            FUNCTION NARROW(KPLUS,KMINUS,N,R) RESULT(NARROW_0)
              REAL(KIND=8), INTENT(IN) :: KPLUS(3,3,3)
              REAL(KIND=8), INTENT(IN) :: KMINUS(3,3,3)
              INTEGER(KIND=4), INTENT(IN) :: N
              REAL(KIND=8), INTENT(OUT) :: R(3,3)
              LOGICAL(KIND=4) :: NARROW_0
            END FUNCTION NARROW
          END INTERFACE 
        END MODULE NARROW_mod
