        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:47 2014
        MODULE NEIGHBOR__genmod
          INTERFACE 
            FUNCTION NEIGHBOR(ELEMNT,EDG)
              INTEGER(KIND=4), INTENT(IN) :: ELEMNT
              INTEGER(KIND=4), INTENT(IN) :: EDG
              INTEGER(KIND=4) :: NEIGHBOR
            END FUNCTION NEIGHBOR
          END INTERFACE 
        END MODULE NEIGHBOR__genmod
