        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:55 2009
        MODULE NEIGHBOR_mod
          INTERFACE 
            FUNCTION NEIGHBOR(ELEMNT,EDG) RESULT(NEIGHBOR_0)
              INTEGER(KIND=4), INTENT(IN) :: ELEMNT
              INTEGER(KIND=4), INTENT(IN) :: EDG
              INTEGER(KIND=4) :: NEIGHBOR_0
            END FUNCTION NEIGHBOR
          END INTERFACE 
        END MODULE NEIGHBOR_mod
