        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:15 2009
        MODULE NODE_DB_mod
          INTERFACE 
            SUBROUTINE NODE_DB
          END SUBROUTINE NODE_DB
        END INTERFACE 
      END MODULE NODE_DB_mod
