        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:20 2009
        MODULE NODE_IN_BDRY_mod
          INTERFACE 
            FUNCTION NODE_IN_BDRY(PTO,E1,E2) RESULT(NODE_IN_BDRY_0)
              INTEGER(KIND=4), INTENT(IN) :: PTO
              INTEGER(KIND=4), INTENT(OUT) :: E1
              INTEGER(KIND=4), INTENT(OUT) :: E2
              LOGICAL(KIND=4) :: NODE_IN_BDRY_0
            END FUNCTION NODE_IN_BDRY
          END INTERFACE 
        END MODULE NODE_IN_BDRY_mod
