        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:48:02 2009
        MODULE NODE_IN_TRIANG_mod
          INTERFACE 
            FUNCTION NODE_IN_TRIANG(N,T) RESULT(NODE_IN_TRIANG_0)
            INTEGER(KIND=4), INTENT(IN) :: N
            TYPE (TRIANGLE), INTENT(IN) :: T
            LOGICAL(KIND=4) :: NODE_IN_TRIANG_0
          END FUNCTION NODE_IN_TRIANG
        END INTERFACE 
      END MODULE NODE_IN_TRIANG_mod
