        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:33 2014
        MODULE NODE_DB__genmod
          INTERFACE 
            SUBROUTINE NODE_DB
              USE GEOMETRY
            END SUBROUTINE NODE_DB
          END INTERFACE 
        END MODULE NODE_DB__genmod
