        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:09 2009
        MODULE NONLINEARB_mod
          INTERFACE 
            FUNCTION NONLINEARB(KPLUS,KMINUS,N,R) RESULT(NONLINEARB_0)
              REAL(KIND=8), INTENT(IN) :: KPLUS(3,3,3)
              REAL(KIND=8), INTENT(IN) :: KMINUS(3,3,3)
              INTEGER(KIND=4), INTENT(IN) :: N
              REAL(KIND=8), INTENT(OUT) :: R(3,3)
              LOGICAL(KIND=4) :: NONLINEARB_0
            END FUNCTION NONLINEARB
          END INTERFACE 
        END MODULE NONLINEARB_mod
