        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:03 2009
        MODULE OUTPUT_DATAV_mod
          INTERFACE 
            SUBROUTINE OUTPUT_DATAV(ITERMAX,RESMAX,TITLE)
              INTEGER(KIND=4), INTENT(IN) :: ITERMAX
              REAL(KIND=8), INTENT(IN) :: RESMAX
              CHARACTER(*) :: TITLE
            END SUBROUTINE OUTPUT_DATAV
          END INTERFACE 
        END MODULE OUTPUT_DATAV_mod
