        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:58 2009
        MODULE PART_DRY_mod
          INTERFACE 
            FUNCTION PART_DRY(E,N,I,J) RESULT(PART_DRY_0)
            TYPE (TRIANGLE), INTENT(IN) :: E
            INTEGER(KIND=4), INTENT(OUT) :: N
            INTEGER(KIND=4), INTENT(OUT) :: I
            INTEGER(KIND=4), INTENT(OUT) :: J
            LOGICAL(KIND=4) :: PART_DRY_0
          END FUNCTION PART_DRY
        END INTERFACE 
      END MODULE PART_DRY_mod
