        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:20 2009
        MODULE PHISUBT_mod
          INTERFACE 
            SUBROUTINE PHISUBT(PHIT)
            REAL(KIND=8), INTENT(OUT) :: PHIT(N_ELEMS,3)
          END SUBROUTINE PHISUBT
        END INTERFACE 
      END MODULE PHISUBT_mod
