        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:40:02 2014
        MODULE POSITIVITY_VTX__genmod
          INTERFACE 
            SUBROUTINE POSITIVITY_VTX
            END SUBROUTINE POSITIVITY_VTX
          END INTERFACE 
        END MODULE POSITIVITY_VTX__genmod
