        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:47 2009
        MODULE POSITIVITY_VTX_mod
          INTERFACE 
            SUBROUTINE POSITIVITY_VTX
            END SUBROUTINE POSITIVITY_VTX
          END INTERFACE 
        END MODULE POSITIVITY_VTX_mod
