        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:25 2014
        MODULE PROBEFILEH__genmod
          INTERFACE 
            FUNCTION PROBEFILEH
              INTEGER(KIND=4) :: PROBEFILEH
            END FUNCTION PROBEFILEH
          END INTERFACE 
        END MODULE PROBEFILEH__genmod
