        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:45:38 2009
        MODULE PROBEFILEH_mod
          INTERFACE 
            FUNCTION PROBEFILEH RESULT(PROBEFILEH_0)
              INTEGER(KIND=4) :: PROBEFILEH_0
            END FUNCTION PROBEFILEH
          END INTERFACE 
        END MODULE PROBEFILEH_mod
