        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:47:59 2009
        MODULE PTO_IN_EDGE_mod
          INTERFACE 
            FUNCTION PTO_IN_EDGE(I,E) RESULT(PTO_IN_EDGE_0)
            INTEGER(KIND=4), INTENT(IN) :: I
            TYPE (EDGE), INTENT(IN) :: E
            LOGICAL(KIND=4) :: PTO_IN_EDGE_0
          END FUNCTION PTO_IN_EDGE
        END INTERFACE 
      END MODULE PTO_IN_EDGE_mod
