        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:48 2009
        MODULE QUERY_mod
          INTERFACE 
            FUNCTION QUERY(Q) RESULT(QUERY_0)
              LOGICAL(KIND=4) :: Q
              INTEGER(KIND=4) :: QUERY_0
            END FUNCTION QUERY
          END INTERFACE 
        END MODULE QUERY_mod
