        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:47:15 2009
        MODULE READ_DATA_mod
          INTERFACE 
            SUBROUTINE READ_DATA(FILENAME,TITLE)
              CHARACTER(*), INTENT(OUT) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_DATA
          END INTERFACE 
        END MODULE READ_DATA_mod
