        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:49 2009
        MODULE READLINE_mod
          INTERFACE 
            FUNCTION READLINE(FUNIT,LINE,LINENO) RESULT(READLINE_0)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
              CHARACTER(LEN=40), INTENT(OUT) :: LINE
              INTEGER(KIND=4), INTENT(INOUT) :: LINENO
              LOGICAL(KIND=4) :: READLINE_0
            END FUNCTION READLINE
          END INTERFACE 
        END MODULE READLINE_mod
