        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:13 2014
        MODULE READLINE__genmod
          INTERFACE 
            FUNCTION READLINE(FUNIT,LINE,LINENO)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
              CHARACTER(LEN=40), INTENT(OUT) :: LINE
              INTEGER(KIND=4), INTENT(INOUT) :: LINENO
              LOGICAL(KIND=4) :: READLINE
            END FUNCTION READLINE
          END INTERFACE 
        END MODULE READLINE__genmod
