        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:12 2009
        MODULE READ_OPTIONS_CGNS_mod
          INTERFACE 
            SUBROUTINE READ_OPTIONS_CGNS(IFILE,IBASE,IZONE,IUSER)
              INTEGER(KIND=4), INTENT(IN) :: IFILE
              INTEGER(KIND=4), INTENT(IN) :: IBASE
              INTEGER(KIND=4), INTENT(IN) :: IZONE
              INTEGER(KIND=4), INTENT(IN) :: IUSER
            END SUBROUTINE READ_OPTIONS_CGNS
          END INTERFACE 
        END MODULE READ_OPTIONS_CGNS_mod
