        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:49 2009
        MODULE READ_CGNS_mod
          INTERFACE 
            SUBROUTINE READ_CGNS(FILENAME,TITLE)
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_CGNS
          END INTERFACE 
        END MODULE READ_CGNS_mod
