        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:37 2014
        MODULE READ_MFA__genmod
          INTERFACE 
            SUBROUTINE READ_MFA(FILENAME,TITLE)
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_MFA
          END INTERFACE 
        END MODULE READ_MFA__genmod
