        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:42 2014
        MODULE READ_CGNS__genmod
          INTERFACE 
            SUBROUTINE READ_CGNS(FILENAME,TITLE)
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_CGNS
          END INTERFACE 
        END MODULE READ_CGNS__genmod
