        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:54 2009
        MODULE READ_MFA_mod
          INTERFACE 
            SUBROUTINE READ_MFA(FILENAME,TITLE)
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_MFA
          END INTERFACE 
        END MODULE READ_MFA_mod
