        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:46 2009
        MODULE READP_mod
          INTERFACE 
            FUNCTION READP(STRING) RESULT(READP_0)
              CHARACTER(*), INTENT(INOUT) :: STRING
              INTEGER(KIND=4) :: READP_0
            END FUNCTION READP
          END INTERFACE 
        END MODULE READP_mod
