        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:45:41 2009
        MODULE READ_OPTIONS_mod
          INTERFACE 
            SUBROUTINE READ_OPTIONS(FUNIT)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
            END SUBROUTINE READ_OPTIONS
          END INTERFACE 
        END MODULE READ_OPTIONS_mod
