        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:40:05 2014
        MODULE READ_OPTIONS__genmod
          INTERFACE 
            SUBROUTINE READ_OPTIONS(FUNIT)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
            END SUBROUTINE READ_OPTIONS
          END INTERFACE 
        END MODULE READ_OPTIONS__genmod
