        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:24 2014
        MODULE READ_DATA__genmod
          INTERFACE 
            SUBROUTINE READ_DATA(FILENAME,TITLE)
              CHARACTER(*), INTENT(OUT) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_DATA
          END INTERFACE 
        END MODULE READ_DATA__genmod
