        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:28 2009
        MODULE RESIDUALS_mod
          INTERFACE 
            SUBROUTINE RESIDUALS
            END SUBROUTINE RESIDUALS
          END INTERFACE 
        END MODULE RESIDUALS_mod
