        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:38 2014
        MODULE RESIDUALS__genmod
          INTERFACE 
            SUBROUTINE RESIDUALS
            END SUBROUTINE RESIDUALS
          END INTERFACE 
        END MODULE RESIDUALS__genmod
