        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:14 2014
        MODULE RMV_ARRAY_PTO__genmod
          INTERFACE 
            SUBROUTINE RMV_ARRAY_PTO(I,N,IARRAY)
              INTEGER(KIND=4), INTENT(INOUT) :: N
              INTEGER(KIND=4), INTENT(IN) :: I
              INTEGER(KIND=4), INTENT(INOUT) :: IARRAY(N)
            END SUBROUTINE RMV_ARRAY_PTO
          END INTERFACE 
        END MODULE RMV_ARRAY_PTO__genmod
