        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:32 2014
        MODULE RVEGDATA__genmod
          INTERFACE 
            SUBROUTINE RVEGDATA
            END SUBROUTINE RVEGDATA
          END INTERFACE 
        END MODULE RVEGDATA__genmod
