        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:19 2009
        MODULE RVEGDATA_mod
          INTERFACE 
            SUBROUTINE RVEGDATA
            END SUBROUTINE RVEGDATA
          END INTERFACE 
        END MODULE RVEGDATA_mod
