        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:47:32 2009
        MODULE SELECT_OUT_mod
          INTERFACE 
            FUNCTION SELECT_OUT(ITER) RESULT(SELECT_OUT_0)
              INTEGER(KIND=4), INTENT(IN) :: ITER
              LOGICAL(KIND=4) :: SELECT_OUT_0
            END FUNCTION SELECT_OUT
          END INTERFACE 
        END MODULE SELECT_OUT_mod
