        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:29 2014
        MODULE SHIELDS_DIAMETER__genmod
          INTERFACE 
            SUBROUTINE SHIELDS_DIAMETER(D,TAU,DEPTH)
              USE GEOMETRY
              REAL(KIND=8), INTENT(OUT) :: D(N_PTS)
              REAL(KIND=8) :: TAU(N_PTS)
              REAL(KIND=8) :: DEPTH(N_PTS)
            END SUBROUTINE SHIELDS_DIAMETER
          END INTERFACE 
        END MODULE SHIELDS_DIAMETER__genmod
