        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:19 2014
        MODULE SHIELDS_TAU__genmod
          INTERFACE 
            FUNCTION SHIELDS_TAU(D)
              REAL(KIND=8), INTENT(IN) :: D
              REAL(KIND=8) :: SHIELDS_TAU
            END FUNCTION SHIELDS_TAU
          END INTERFACE 
        END MODULE SHIELDS_TAU__genmod
