        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:48:04 2009
        MODULE SKIN_FRICTION_mod
          INTERFACE 
            FUNCTION SKIN_FRICTION(FTYPE,FFACTOR,DEPTH,VEL,NU,VEGC1,    &
     &VEGC2) RESULT(SKIN_FRICTION_0)
              INTEGER(KIND=4), INTENT(IN) :: FTYPE
              REAL(KIND=8), INTENT(IN) :: FFACTOR
              REAL(KIND=8), INTENT(IN) :: DEPTH
              REAL(KIND=8), INTENT(IN) :: VEL
              REAL(KIND=8), INTENT(IN) :: NU
              REAL(KIND=8), INTENT(IN) :: VEGC1
              REAL(KIND=8), INTENT(IN) :: VEGC2
              REAL(KIND=8) :: SKIN_FRICTION_0
            END FUNCTION SKIN_FRICTION
          END INTERFACE 
        END MODULE SKIN_FRICTION_mod
