        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:03 2009
        MODULE SOLVERRDS_mod
          INTERFACE 
            SUBROUTINE SOLVERRDS(ITER,RMAX,FN,TITLE)
              INTEGER(KIND=4), INTENT(OUT) :: ITER
              REAL(KIND=8), INTENT(OUT) :: RMAX
              CHARACTER(*), INTENT(IN) :: FN
              CHARACTER(*), INTENT(IN) :: TITLE
            END SUBROUTINE SOLVERRDS
          END INTERFACE 
        END MODULE SOLVERRDS_mod
