        !COMPILER-GENERATED INTERFACE MODULE: Mon Jul 18 14:09:45 2016
        MODULE SOLVERFVT__genmod
          INTERFACE 
            SUBROUTINE SOLVERFVT(ITER,TTIME,RMAX,FN,TITLE)
              INTEGER(KIND=4), INTENT(OUT) :: ITER
              REAL(KIND=8), INTENT(OUT) :: TTIME
              REAL(KIND=8), INTENT(OUT) :: RMAX
              CHARACTER(*), INTENT(IN) :: FN
              CHARACTER(*), INTENT(IN) :: TITLE
            END SUBROUTINE SOLVERFVT
          END INTERFACE 
        END MODULE SOLVERFVT__genmod
