        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 12 14:27:47 2009
        MODULE SOLVERFVT_mod
          INTERFACE 
            SUBROUTINE SOLVERFVT(ITER,TTIME,RMAX,FN,TITLE)
              INTEGER(KIND=4), INTENT(OUT) :: ITER
              REAL(KIND=8), INTENT(OUT) :: TTIME
              REAL(KIND=8), INTENT(OUT) :: RMAX
              CHARACTER(*), INTENT(IN) :: FN
              CHARACTER(*), INTENT(IN) :: TITLE
            END SUBROUTINE SOLVERFVT
          END INTERFACE 
        END MODULE SOLVERFVT_mod
