        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:25 2009
        MODULE SPIT_OUT_mod
          INTERFACE 
            SUBROUTINE SPIT_OUT(ITER,FNAME,T)
              INTEGER(KIND=4), INTENT(IN) :: ITER
              CHARACTER(*) :: FNAME
              CHARACTER(*) :: T
            END SUBROUTINE SPIT_OUT
          END INTERFACE 
        END MODULE SPIT_OUT_mod
