        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:47 2009
        MODULE STRIP_EXT_mod
          INTERFACE 
            SUBROUTINE STRIP_EXT(FN)
              CHARACTER(*), INTENT(INOUT) :: FN
            END SUBROUTINE STRIP_EXT
          END INTERFACE 
        END MODULE STRIP_EXT_mod
