        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:48:01 2009
        MODULE T_AREAS_mod
          INTERFACE 
            SUBROUTINE T_AREAS(GRID,NGRID,PTO,NPTO,EDG,NEDG)
            INTEGER(KIND=4), INTENT(IN) :: NEDG
            INTEGER(KIND=4), INTENT(IN) :: NPTO
            INTEGER(KIND=4), INTENT(IN) :: NGRID
            TYPE (TRIANGLE) :: GRID(NGRID)
            TYPE (POINT) :: PTO(NPTO)
            TYPE (EDGE) :: EDG(NEDG)
          END SUBROUTINE T_AREAS
        END INTERFACE 
      END MODULE T_AREAS_mod
