        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:47 2014
        MODULE TECPLOT_READ__genmod
          INTERFACE 
            SUBROUTINE TECPLOT_READ(ID,VARLOC)
              INTEGER(KIND=4), INTENT(IN) :: ID
              CHARACTER(*), INTENT(IN) :: VARLOC
            END SUBROUTINE TECPLOT_READ
          END INTERFACE 
        END MODULE TECPLOT_READ__genmod
