        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:06 2009
        MODULE TECPLOT_mod
          INTERFACE 
            SUBROUTINE TECPLOT(ID)
              INTEGER(KIND=4), INTENT(IN) :: ID
            END SUBROUTINE TECPLOT
          END INTERFACE 
        END MODULE TECPLOT_mod
