        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:44 2014
        MODULE TECPLOT_WRITE__genmod
          INTERFACE 
            SUBROUTINE TECPLOT_WRITE(ID)
              INTEGER(KIND=4), INTENT(IN) :: ID
            END SUBROUTINE TECPLOT_WRITE
          END INTERFACE 
        END MODULE TECPLOT_WRITE__genmod
