        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 12 13:59:29 2009
        MODULE TECPLOT_WRITE_mod
          INTERFACE 
            SUBROUTINE TECPLOT_WRITE(ID)
              INTEGER(KIND=4), INTENT(IN) :: ID
            END SUBROUTINE TECPLOT_WRITE
          END INTERFACE 
        END MODULE TECPLOT_WRITE_mod
