        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:27 2009
        MODULE TECPLOT_READ_mod
          INTERFACE 
            SUBROUTINE TECPLOT_READ(ID,VARLOC)
              INTEGER(KIND=4), INTENT(IN) :: ID
              CHARACTER(*), INTENT(IN) :: VARLOC
            END SUBROUTINE TECPLOT_READ
          END INTERFACE 
        END MODULE TECPLOT_READ_mod
