        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:21 2014
        MODULE TECPLOT__genmod
          INTERFACE 
            SUBROUTINE TECPLOT(ID)
              INTEGER(KIND=4), INTENT(IN) :: ID
            END SUBROUTINE TECPLOT
          END INTERFACE 
        END MODULE TECPLOT__genmod
