        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 23 13:46:47 2009
        MODULE TO_UPPER_mod
          INTERFACE 
            FUNCTION TO_UPPER(CH) RESULT(TO_UPPER_0)
              CHARACTER(LEN=1), INTENT(IN) :: CH
              CHARACTER(LEN=1) :: TO_UPPER_0
            END FUNCTION TO_UPPER
          END INTERFACE 
        END MODULE TO_UPPER_mod
