        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:13 2014
        MODULE TO_UPPER__genmod
          INTERFACE 
            FUNCTION TO_UPPER(CH)
              CHARACTER(LEN=1), INTENT(IN) :: CH
              CHARACTER(LEN=1) :: TO_UPPER
            END FUNCTION TO_UPPER
          END INTERFACE 
        END MODULE TO_UPPER__genmod
