        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:28 2014
        MODULE TO_VERTICES__genmod
          INTERFACE 
            SUBROUTINE TO_VERTICES
            END SUBROUTINE TO_VERTICES
          END INTERFACE 
        END MODULE TO_VERTICES__genmod
