        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:34 2014
        MODULE VCROP__genmod
          INTERFACE 
            SUBROUTINE VCROP(VCLIP,VCEILING)
              LOGICAL(KIND=4), INTENT(IN) :: VCLIP
              REAL(KIND=8), INTENT(IN) :: VCEILING
            END SUBROUTINE VCROP
          END INTERFACE 
        END MODULE VCROP__genmod
