        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 12 11:26:34 2009
        MODULE VISC_FLUXES_mod
          INTERFACE 
            SUBROUTINE VISC_FLUXES
            END SUBROUTINE VISC_FLUXES
          END INTERFACE 
        END MODULE VISC_FLUXES_mod
