        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:40:04 2014
        MODULE VISC_TERMS__genmod
          INTERFACE 
            SUBROUTINE VISC_TERMS
            END SUBROUTINE VISC_TERMS
          END INTERFACE 
        END MODULE VISC_TERMS__genmod
