        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:41 2009
        MODULE VISC_TERMS_mod
          INTERFACE 
            SUBROUTINE VISC_TERMS
            END SUBROUTINE VISC_TERMS
          END INTERFACE 
        END MODULE VISC_TERMS_mod
