        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 02 12:45:35 2009
        MODULE VISCOSITY_mod
          INTERFACE 
            FUNCTION VISCOSITY(T) RESULT(VISCOSITY_0)
              REAL(KIND=8), INTENT(IN) :: T
              REAL(KIND=8) :: VISCOSITY_0
            END FUNCTION VISCOSITY
          END INTERFACE 
        END MODULE VISCOSITY_mod
