        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:26 2014
        MODULE VISC_FLUXES__genmod
          INTERFACE 
            SUBROUTINE VISC_FLUXES
            END SUBROUTINE VISC_FLUXES
          END INTERFACE 
        END MODULE VISC_FLUXES__genmod
