        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:24 2009
        MODULE VTX2CTR_mod
          INTERFACE 
            SUBROUTINE VTX2CTR(VARRAY,CARRAY)
            REAL(KIND=8), INTENT(IN) :: VARRAY(N_PTS)
            REAL(KIND=8), INTENT(OUT) :: CARRAY(N_ELEMS)
          END SUBROUTINE VTX2CTR
        END INTERFACE 
      END MODULE VTX2CTR_mod
