        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:48 2014
        MODULE VTX2CTR__genmod
          INTERFACE 
            SUBROUTINE VTX2CTR(VARRAY,CARRAY)
              USE GEOMETRY
              REAL(KIND=8), INTENT(IN) :: VARRAY(N_PTS)
              REAL(KIND=8), INTENT(OUT) :: CARRAY(N_ELEMS)
            END SUBROUTINE VTX2CTR
          END INTERFACE 
        END MODULE VTX2CTR__genmod
