        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:54 2009
        MODULE WALLS_mod
          INTERFACE 
            SUBROUTINE WALLS
          END SUBROUTINE WALLS
        END INTERFACE 
      END MODULE WALLS_mod
