        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:40:01 2014
        MODULE WENSLP_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WENSLP_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP_FLUXES
          END INTERFACE 
        END MODULE WENSLP_FLUXES__genmod
