        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:21 2014
        MODULE WENSLP3_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WENSLP3_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP3_FLUXES
          END INTERFACE 
        END MODULE WENSLP3_FLUXES__genmod
