        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:15 2009
        MODULE WENSLP2_FLUXES_mod
          INTERFACE 
            SUBROUTINE WENSLP2_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP2_FLUXES
          END INTERFACE 
        END MODULE WENSLP2_FLUXES_mod
