        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:02:45 2009
        MODULE WENSLP3_FLUXES_mod
          INTERFACE 
            SUBROUTINE WENSLP3_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP3_FLUXES
          END INTERFACE 
        END MODULE WENSLP3_FLUXES_mod
