        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:33 2014
        MODULE WENSLP2_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WENSLP2_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP2_FLUXES
          END INTERFACE 
        END MODULE WENSLP2_FLUXES__genmod
