        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:06 2009
        MODULE WENSLP_FLUXES_mod
          INTERFACE 
            SUBROUTINE WENSLP_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP_FLUXES
          END INTERFACE 
        END MODULE WENSLP_FLUXES_mod
