        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:44 2014
        MODULE WESLP_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WESLP_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP_FLUXES
          END INTERFACE 
        END MODULE WESLP_FLUXES__genmod
