        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:31 2009
        MODULE WESLP_FLUXES_mod
          INTERFACE 
            SUBROUTINE WESLP_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP_FLUXES
          END INTERFACE 
        END MODULE WESLP_FLUXES_mod
