        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:09 2009
        MODULE WESLP2_FLUXES_mod
          INTERFACE 
            SUBROUTINE WESLP2_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP2_FLUXES
          END INTERFACE 
        END MODULE WESLP2_FLUXES_mod
