        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 11:39:54 2014
        MODULE WESLP2_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WESLP2_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP2_FLUXES
          END INTERFACE 
        END MODULE WESLP2_FLUXES__genmod
