        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:01 2009
        MODULE WETDRYFIX_mod
          INTERFACE 
            SUBROUTINE WETDRYFIX(ITYPE,HV,HC,GRADHC)
          INTEGER(KIND=4), INTENT(IN) :: ITYPE
          REAL(KIND=8), INTENT(INOUT) :: HV(N_PTS)
          REAL(KIND=8), INTENT(IN) :: HC(N_ELEMS)
          TYPE (VECTOR), INTENT(IN) :: GRADHC(N_ELEMS)
        END SUBROUTINE WETDRYFIX
      END INTERFACE 
    END MODULE WETDRYFIX_mod
