        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 22 12:40:44 2014
        MODULE WRITE_CGNS__genmod
          INTERFACE 
            SUBROUTINE WRITE_CGNS(TTIME)
              REAL(KIND=8), INTENT(IN) :: TTIME
            END SUBROUTINE WRITE_CGNS
          END INTERFACE 
        END MODULE WRITE_CGNS__genmod
