        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 03 18:03:13 2009
        MODULE ZETA_BCS_mod
          INTERFACE 
            SUBROUTINE ZETA_BCS
            END SUBROUTINE ZETA_BCS
          END INTERFACE 
        END MODULE ZETA_BCS_mod
