        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 07 13:43:27 2014
        MODULE ZETA_BCS__genmod
          INTERFACE 
            SUBROUTINE ZETA_BCS
            END SUBROUTINE ZETA_BCS
          END INTERFACE 
        END MODULE ZETA_BCS__genmod
