        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:05 2018
        MODULE ADD_ARRAY_PTOT__genmod
          INTERFACE 
            SUBROUTINE ADD_ARRAY_PTOT(I,N,IARRAY)
              INTEGER(KIND=4), INTENT(INOUT) :: N
              INTEGER(KIND=4), INTENT(IN) :: I
              INTEGER(KIND=4), INTENT(INOUT) :: IARRAY(N+1)
            END SUBROUTINE ADD_ARRAY_PTOT
          END INTERFACE 
        END MODULE ADD_ARRAY_PTOT__genmod
