        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:46 2018
        MODULE ADJUST_BED_ELEVATION__genmod
          INTERFACE 
            SUBROUTINE ADJUST_BED_ELEVATION(ZCHANGE)
              LOGICAL(KIND=4), INTENT(OUT) :: ZCHANGE
            END SUBROUTINE ADJUST_BED_ELEVATION
          END INTERFACE 
        END MODULE ADJUST_BED_ELEVATION__genmod
