        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:33 2018
        MODULE ADJUST_WATER_DEPTH__genmod
          INTERFACE 
            SUBROUTINE ADJUST_WATER_DEPTH
            END SUBROUTINE ADJUST_WATER_DEPTH
          END INTERFACE 
        END MODULE ADJUST_WATER_DEPTH__genmod
