        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:52 2018
        MODULE AZIMUTH2ANGLE__genmod
          INTERFACE 
            FUNCTION AZIMUTH2ANGLE(X)
              REAL(KIND=8), INTENT(IN) :: X
              REAL(KIND=8) :: AZIMUTH2ANGLE
            END FUNCTION AZIMUTH2ANGLE
          END INTERFACE 
        END MODULE AZIMUTH2ANGLE__genmod
