        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:58 2018
        MODULE BED_SLOPE_STD__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_STD
            END SUBROUTINE BED_SLOPE_STD
          END INTERFACE 
        END MODULE BED_SLOPE_STD__genmod
