        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:49 2018
        MODULE BED_SLOPE_VTX__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_VTX
            END SUBROUTINE BED_SLOPE_VTX
          END INTERFACE 
        END MODULE BED_SLOPE_VTX__genmod
