        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:31 2018
        MODULE BED_SLOPE__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE
            END SUBROUTINE BED_SLOPE
          END INTERFACE 
        END MODULE BED_SLOPE__genmod
