        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:13:06 2018
        MODULE BED_SLOPE_ETA__genmod
          INTERFACE 
            SUBROUTINE BED_SLOPE_ETA(SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE BED_SLOPE_ETA
          END INTERFACE 
        END MODULE BED_SLOPE_ETA__genmod
