        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:52 2018
        MODULE C2V_SETUP__genmod
          INTERFACE 
            SUBROUTINE C2V_SETUP(TYPE)
              INTEGER(KIND=4), INTENT(IN) :: TYPE
            END SUBROUTINE C2V_SETUP
          END INTERFACE 
        END MODULE C2V_SETUP__genmod
