        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:04 2018
        MODULE CCSTRING__genmod
          INTERFACE 
            FUNCTION CCSTRING(A,N,STRING)
              INTEGER(KIND=4), INTENT(IN) :: N
              LOGICAL(KIND=4), INTENT(IN) :: A(N)
              CHARACTER(*), INTENT(OUT) :: STRING
              INTEGER(KIND=4) :: CCSTRING
            END FUNCTION CCSTRING
          END INTERFACE 
        END MODULE CCSTRING__genmod
