        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:10 2018
        MODULE CELL_CENTERED__genmod
          INTERFACE 
            FUNCTION CELL_CENTERED(VAR,STRING)
              CHARACTER(*), INTENT(IN) :: VAR
              CHARACTER(*), INTENT(IN) :: STRING
              LOGICAL(KIND=4) :: CELL_CENTERED
            END FUNCTION CELL_CENTERED
          END INTERFACE 
        END MODULE CELL_CENTERED__genmod
