        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:33 2018
        MODULE CHAN_ARRAYS__genmod
          INTERFACE 
            SUBROUTINE CHAN_ARRAYS
            END SUBROUTINE CHAN_ARRAYS
          END INTERFACE 
        END MODULE CHAN_ARRAYS__genmod
