        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:46 2018
        MODULE CRIT_OUTFLOW__genmod
          INTERFACE 
            SUBROUTINE CRIT_OUTFLOW
            END SUBROUTINE CRIT_OUTFLOW
          END INTERFACE 
        END MODULE CRIT_OUTFLOW__genmod
