        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:40 2018
        MODULE CTR2VTXWSE__genmod
          INTERFACE 
            SUBROUTINE CTR2VTXWSE(TYPE,CARRAY,VARRAY)
              USE GEOMETRY
              INTEGER(KIND=4), INTENT(IN) :: TYPE
              REAL(KIND=8), INTENT(IN) :: CARRAY(N_ELEMS)
              REAL(KIND=8), INTENT(OUT) :: VARRAY(N_PTS)
            END SUBROUTINE CTR2VTXWSE
          END INTERFACE 
        END MODULE CTR2VTXWSE__genmod
