        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:28 2018
        MODULE CVDISCH__genmod
          INTERFACE 
            SUBROUTINE CVDISCH
            END SUBROUTINE CVDISCH
          END INTERFACE 
        END MODULE CVDISCH__genmod
