        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:13:06 2018
        MODULE DELTAT__genmod
          INTERFACE 
            FUNCTION DELTAT(CRTYPE,CFL)
              INTEGER(KIND=4), INTENT(IN) :: CRTYPE
              REAL(KIND=8), INTENT(IN) :: CFL
              REAL(KIND=8) :: DELTAT
            END FUNCTION DELTAT
          END INTERFACE 
        END MODULE DELTAT__genmod
