        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:30 2018
        MODULE DIRICHLET__genmod
          INTERFACE 
            SUBROUTINE DIRICHLET(I,RKSTEP)
              INTEGER(KIND=4), INTENT(IN) :: I
              INTEGER(KIND=4), INTENT(IN) :: RKSTEP
            END SUBROUTINE DIRICHLET
          END INTERFACE 
        END MODULE DIRICHLET__genmod
