        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:28 2018
        MODULE DISTRIBUTION__genmod
          INTERFACE 
            FUNCTION DISTRIBUTION
              INTEGER(KIND=4) :: DISTRIBUTION
            END FUNCTION DISTRIBUTION
          END INTERFACE 
        END MODULE DISTRIBUTION__genmod
