        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:58 2018
        MODULE DRYNWET__genmod
          INTERFACE 
            SUBROUTINE DRYNWET(E,ZOUT)
              USE PARAMETERS
              TYPE (TRIANGLE), INTENT(IN) :: E
              REAL(KIND=8), INTENT(OUT) :: ZOUT(3)
            END SUBROUTINE DRYNWET
          END INTERFACE 
        END MODULE DRYNWET__genmod
