        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:42 2018
        MODULE EDDY_VISCOSITY__genmod
          INTERFACE 
            SUBROUTINE EDDY_VISCOSITY
            END SUBROUTINE EDDY_VISCOSITY
          END INTERFACE 
        END MODULE EDDY_VISCOSITY__genmod
