        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:32 2018
        MODULE ERROR_EST__genmod
          INTERFACE 
            SUBROUTINE ERROR_EST(ETYPE)
              INTEGER(KIND=4) :: ETYPE
            END SUBROUTINE ERROR_EST
          END INTERFACE 
        END MODULE ERROR_EST__genmod
