        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:05 2018
        MODULE FINDTTCHECK__genmod
          INTERFACE 
            FUNCTION FINDTTCHECK(STRG)
              CHARACTER(*), INTENT(IN) :: STRG
              LOGICAL(KIND=4) :: FINDTTCHECK
            END FUNCTION FINDTTCHECK
          END INTERFACE 
        END MODULE FINDTTCHECK__genmod
