        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:28 2018
        MODULE FIND_EDGES__genmod
          INTERFACE 
            SUBROUTINE FIND_EDGES
            END SUBROUTINE FIND_EDGES
          END INTERFACE 
        END MODULE FIND_EDGES__genmod
