        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:25 2018
        MODULE FIND_DRY_CELLS__genmod
          INTERFACE 
            SUBROUTINE FIND_DRY_CELLS
            END SUBROUTINE FIND_DRY_CELLS
          END INTERFACE 
        END MODULE FIND_DRY_CELLS__genmod
