        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:32 2018
        MODULE FLOOD_CHAN__genmod
          INTERFACE 
            SUBROUTINE FLOOD_CHAN(T)
              REAL(KIND=8) :: T
            END SUBROUTINE FLOOD_CHAN
          END INTERFACE 
        END MODULE FLOOD_CHAN__genmod
