        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:08 2018
        MODULE FNAMES__genmod
          INTERFACE 
            FUNCTION FNAMES(FUNIT,FNAME)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
              CHARACTER(LEN=80), INTENT(OUT) :: FNAME
              LOGICAL(KIND=4) :: FNAMES
            END FUNCTION FNAMES
          END INTERFACE 
        END MODULE FNAMES__genmod
