        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:42 2018
        MODULE FRIC_TERMS__genmod
          INTERFACE 
            SUBROUTINE FRIC_TERMS
            END SUBROUTINE FRIC_TERMS
          END INTERFACE 
        END MODULE FRIC_TERMS__genmod
