        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:42 2018
        MODULE FRIC_TERMS_IMPL__genmod
          INTERFACE 
            SUBROUTINE FRIC_TERMS_IMPL(DELTA_T)
              REAL(KIND=8), INTENT(IN) :: DELTA_T
            END SUBROUTINE FRIC_TERMS_IMPL
          END INTERFACE 
        END MODULE FRIC_TERMS_IMPL__genmod
