        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:13:01 2018
        MODULE FRIC_SLOPE__genmod
          INTERFACE 
            SUBROUTINE FRIC_SLOPE
            END SUBROUTINE FRIC_SLOPE
          END INTERFACE 
        END MODULE FRIC_SLOPE__genmod
