        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:13:05 2018
        MODULE GET_TIME_BCS__genmod
          INTERFACE 
            SUBROUTINE GET_TIME_BCS(TIME)
              REAL(KIND=8), INTENT(IN) :: TIME
            END SUBROUTINE GET_TIME_BCS
          END INTERFACE 
        END MODULE GET_TIME_BCS__genmod
