        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:13:00 2018
        MODULE GRADHORDR__genmod
          INTERFACE 
            SUBROUTINE GRADHORDR(FEGRAD,GRADPHI)
              USE GEOMETRY
              REAL(KIND=8), INTENT(IN) :: FEGRAD(N_ELEMS,2)
              REAL(KIND=8), INTENT(OUT) :: GRADPHI(N_ELEMS,2)
            END SUBROUTINE GRADHORDR
          END INTERFACE 
        END MODULE GRADHORDR__genmod
