        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:35 2018
        MODULE GRAD__genmod
          INTERFACE 
            SUBROUTINE GRAD(PHI,NVDIM,GRADPHI,NEDIM)
              INTEGER(KIND=4), INTENT(IN) :: NEDIM
              INTEGER(KIND=4), INTENT(IN) :: NVDIM
              REAL(KIND=8), INTENT(IN) :: PHI(NVDIM)
              REAL(KIND=8), INTENT(OUT) :: GRADPHI(NEDIM,2)
            END SUBROUTINE GRAD
          END INTERFACE 
        END MODULE GRAD__genmod
