        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:13:02 2018
        MODULE HDLSQ_GRAD_ARRAY4H__genmod
          INTERFACE 
            SUBROUTINE HDLSQ_GRAD_ARRAY4H
            END SUBROUTINE HDLSQ_GRAD_ARRAY4H
          END INTERFACE 
        END MODULE HDLSQ_GRAD_ARRAY4H__genmod
