        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:54 2018
        MODULE HDLSQ_SETUP__genmod
          INTERFACE 
            SUBROUTINE HDLSQ_SETUP(WTYPE)
              INTEGER(KIND=4), INTENT(IN) :: WTYPE
            END SUBROUTINE HDLSQ_SETUP
          END INTERFACE 
        END MODULE HDLSQ_SETUP__genmod
