        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:32 2018
        MODULE HDLSQ_GRAD_ARRAY__genmod
          INTERFACE 
            SUBROUTINE HDLSQ_GRAD_ARRAY(PHI,GRADPHI,NDIM)
              USE PARAMETERS
              INTEGER(KIND=4), INTENT(IN) :: NDIM
              REAL(KIND=8), INTENT(IN) :: PHI(NDIM)
              TYPE (VECTOR), INTENT(OUT) :: GRADPHI(NDIM)
            END SUBROUTINE HDLSQ_GRAD_ARRAY
          END INTERFACE 
        END MODULE HDLSQ_GRAD_ARRAY__genmod
