        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:57 2018
        MODULE HEADER__genmod
          INTERFACE 
            SUBROUTINE HEADER(ID,FILENAME,TITLE)
              INTEGER(KIND=4), INTENT(IN) :: ID
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE HEADER
          END INTERFACE 
        END MODULE HEADER__genmod
