        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:27 2018
        MODULE HEFFECTIVE__genmod
          INTERFACE 
            FUNCTION HEFFECTIVE(CELL_NO)
              INTEGER(KIND=4), INTENT(IN) :: CELL_NO
              REAL(KIND=8) :: HEFFECTIVE
            END FUNCTION HEFFECTIVE
          END INTERFACE 
        END MODULE HEFFECTIVE__genmod
