        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:13:00 2018
        MODULE HEQUIVALENT__genmod
          INTERFACE 
            SUBROUTINE HEQUIVALENT(E,HLEFT,HRIGHT)
              USE PARAMETERS
              TYPE (EDGE), INTENT(IN) :: E
              REAL(KIND=8), INTENT(INOUT) :: HLEFT
              REAL(KIND=8), INTENT(INOUT) :: HRIGHT
            END SUBROUTINE HEQUIVALENT
          END INTERFACE 
        END MODULE HEQUIVALENT__genmod
