        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:57 2018
        MODULE HGRADFIX2__genmod
          INTERFACE 
            SUBROUTINE HGRADFIX2(RKSTEP,SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: RKSTEP
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE HGRADFIX2
          END INTERFACE 
        END MODULE HGRADFIX2__genmod
