        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:51 2018
        MODULE HOT_START_CGNS__genmod
          INTERFACE 
            SUBROUTINE HOT_START_CGNS(CGNSFILE,N,H,U,V)
              INTEGER(KIND=4), INTENT(IN) :: N
              CHARACTER(*), INTENT(IN) :: CGNSFILE
              REAL(KIND=8), INTENT(OUT) :: H(N)
              REAL(KIND=8), INTENT(OUT) :: U(N)
              REAL(KIND=8), INTENT(OUT) :: V(N)
            END SUBROUTINE HOT_START_CGNS
          END INTERFACE 
        END MODULE HOT_START_CGNS__genmod
