        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:41 2018
        MODULE HOT_START_ASCII__genmod
          INTERFACE 
            SUBROUTINE HOT_START_ASCII
            END SUBROUTINE HOT_START_ASCII
          END INTERFACE 
        END MODULE HOT_START_ASCII__genmod
