        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:24 2018
        MODULE IBC_ARRAYS__genmod
          INTERFACE 
            SUBROUTINE IBC_ARRAYS
            END SUBROUTINE IBC_ARRAYS
          END INTERFACE 
        END MODULE IBC_ARRAYS__genmod
