        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:45 2018
        MODULE INITIALIZE_OPTIONS__genmod
          INTERFACE 
            SUBROUTINE INITIALIZE_OPTIONS
            END SUBROUTINE INITIALIZE_OPTIONS
          END INTERFACE 
        END MODULE INITIALIZE_OPTIONS__genmod
