        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:17 2018
        MODULE INVISC_FLUXES__genmod
          INTERFACE 
            SUBROUTINE INVISC_FLUXES
            END SUBROUTINE INVISC_FLUXES
          END INTERFACE 
        END MODULE INVISC_FLUXES__genmod
