        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:56 2018
        MODULE LSQ_GRAD_ARRAY4H__genmod
          INTERFACE 
            SUBROUTINE LSQ_GRAD_ARRAY4H(SOLVER)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
            END SUBROUTINE LSQ_GRAD_ARRAY4H
          END INTERFACE 
        END MODULE LSQ_GRAD_ARRAY4H__genmod
