        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:34 2018
        MODULE LSQ_SETUP__genmod
          INTERFACE 
            SUBROUTINE LSQ_SETUP(SOLVER,TYPE)
              INTEGER(KIND=4), INTENT(IN) :: SOLVER
              INTEGER(KIND=4), INTENT(IN) :: TYPE
            END SUBROUTINE LSQ_SETUP
          END INTERFACE 
        END MODULE LSQ_SETUP__genmod
