        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:48 2018
        MODULE MARGINS__genmod
          INTERFACE 
            SUBROUTINE MARGINS
            END SUBROUTINE MARGINS
          END INTERFACE 
        END MODULE MARGINS__genmod
