        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:48 2018
        MODULE NEIGHBOR__genmod
          INTERFACE 
            FUNCTION NEIGHBOR(ELEMNT,EDG)
              INTEGER(KIND=4), INTENT(IN) :: ELEMNT
              INTEGER(KIND=4), INTENT(IN) :: EDG
              INTEGER(KIND=4) :: NEIGHBOR
            END FUNCTION NEIGHBOR
          END INTERFACE 
        END MODULE NEIGHBOR__genmod
