        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:16 2018
        MODULE NODE_DB__genmod
          INTERFACE 
            SUBROUTINE NODE_DB
              USE GEOMETRY
            END SUBROUTINE NODE_DB
          END INTERFACE 
        END MODULE NODE_DB__genmod
