        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:46:49 2018
        MODULE OUTPUT_DATA__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_DATA(ITERMAX,TTIME,RESMAX,FILENAME,TITLE)
              INTEGER(KIND=4), INTENT(IN) :: ITERMAX
              REAL(KIND=8), INTENT(IN) :: TTIME
              REAL(KIND=8), INTENT(IN) :: RESMAX
              CHARACTER(*) :: FILENAME
              CHARACTER(*) :: TITLE
            END SUBROUTINE OUTPUT_DATA
          END INTERFACE 
        END MODULE OUTPUT_DATA__genmod
