        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:21 2018
        MODULE OUTPUT_DATAV__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_DATAV(ITERMAX,RESMAX,TITLE)
              INTEGER(KIND=4), INTENT(IN) :: ITERMAX
              REAL(KIND=8), INTENT(IN) :: RESMAX
              CHARACTER(*) :: TITLE
            END SUBROUTINE OUTPUT_DATAV
          END INTERFACE 
        END MODULE OUTPUT_DATAV__genmod
