        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:30 2018
        MODULE POSITIVITY_VTX__genmod
          INTERFACE 
            SUBROUTINE POSITIVITY_VTX
            END SUBROUTINE POSITIVITY_VTX
          END INTERFACE 
        END MODULE POSITIVITY_VTX__genmod
