        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:44 2018
        MODULE PROBEFILEH__genmod
          INTERFACE 
            FUNCTION PROBEFILEH
              INTEGER(KIND=4) :: PROBEFILEH
            END FUNCTION PROBEFILEH
          END INTERFACE 
        END MODULE PROBEFILEH__genmod
