        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 21 13:27:41 2018
        MODULE READ_CGNS__genmod
          INTERFACE 
            SUBROUTINE READ_CGNS(FILENAME,TITLE)
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_CGNS
          END INTERFACE 
        END MODULE READ_CGNS__genmod
