        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:41 2018
        MODULE READ_MFA__genmod
          INTERFACE 
            SUBROUTINE READ_MFA(FILENAME,TITLE)
              CHARACTER(*), INTENT(IN) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_MFA
          END INTERFACE 
        END MODULE READ_MFA__genmod
