        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:20 2018
        MODULE READ_OPTIONS__genmod
          INTERFACE 
            SUBROUTINE READ_OPTIONS(FUNIT)
              INTEGER(KIND=4), INTENT(IN) :: FUNIT
            END SUBROUTINE READ_OPTIONS
          END INTERFACE 
        END MODULE READ_OPTIONS__genmod
