        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:29 2018
        MODULE READ_DATA__genmod
          INTERFACE 
            SUBROUTINE READ_DATA(FILENAME,TITLE)
              CHARACTER(*), INTENT(OUT) :: FILENAME
              CHARACTER(*), INTENT(OUT) :: TITLE
            END SUBROUTINE READ_DATA
          END INTERFACE 
        END MODULE READ_DATA__genmod
