        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:44 2018
        MODULE RESIDUALS__genmod
          INTERFACE 
            SUBROUTINE RESIDUALS
            END SUBROUTINE RESIDUALS
          END INTERFACE 
        END MODULE RESIDUALS__genmod
