        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:29 2018
        MODULE RVEGDATA__genmod
          INTERFACE 
            SUBROUTINE RVEGDATA
            END SUBROUTINE RVEGDATA
          END INTERFACE 
        END MODULE RVEGDATA__genmod
