        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:48 2018
        MODULE SHIELDS_DIAMETER__genmod
          INTERFACE 
            SUBROUTINE SHIELDS_DIAMETER(D,TAU,DEPTH)
              USE GEOMETRY
              REAL(KIND=8), INTENT(OUT) :: D(N_PTS)
              REAL(KIND=8) :: TAU(N_PTS)
              REAL(KIND=8) :: DEPTH(N_PTS)
            END SUBROUTINE SHIELDS_DIAMETER
          END INTERFACE 
        END MODULE SHIELDS_DIAMETER__genmod
