        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:03 2018
        MODULE SORTEDGES__genmod
          INTERFACE 
            FUNCTION SORTEDGES(N,IARRAY)
              INTEGER(KIND=4), INTENT(IN) :: N
              INTEGER(KIND=4), INTENT(INOUT) :: IARRAY(N)
              LOGICAL(KIND=4) :: SORTEDGES
            END FUNCTION SORTEDGES
          END INTERFACE 
        END MODULE SORTEDGES__genmod
