        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:50 2018
        MODULE TECPLOT__genmod
          INTERFACE 
            SUBROUTINE TECPLOT(ID)
              INTEGER(KIND=4), INTENT(IN) :: ID
            END SUBROUTINE TECPLOT
          END INTERFACE 
        END MODULE TECPLOT__genmod
