        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:40 2018
        MODULE TECPLOT_READ__genmod
          INTERFACE 
            SUBROUTINE TECPLOT_READ(ID,VARLOC)
              INTEGER(KIND=4), INTENT(IN) :: ID
              CHARACTER(*), INTENT(IN) :: VARLOC
            END SUBROUTINE TECPLOT_READ
          END INTERFACE 
        END MODULE TECPLOT_READ__genmod
