        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:29 2018
        MODULE TECPLOT_WRITE__genmod
          INTERFACE 
            SUBROUTINE TECPLOT_WRITE(ID)
              INTEGER(KIND=4), INTENT(IN) :: ID
            END SUBROUTINE TECPLOT_WRITE
          END INTERFACE 
        END MODULE TECPLOT_WRITE__genmod
