        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:56 2018
        MODULE TO_VERTICES__genmod
          INTERFACE 
            SUBROUTINE TO_VERTICES
            END SUBROUTINE TO_VERTICES
          END INTERFACE 
        END MODULE TO_VERTICES__genmod
