        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:13:01 2018
        MODULE VISC_TERMS__genmod
          INTERFACE 
            SUBROUTINE VISC_TERMS
            END SUBROUTINE VISC_TERMS
          END INTERFACE 
        END MODULE VISC_TERMS__genmod
