        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:26 2018
        MODULE VISC_FLUXES__genmod
          INTERFACE 
            SUBROUTINE VISC_FLUXES
            END SUBROUTINE VISC_FLUXES
          END INTERFACE 
        END MODULE VISC_FLUXES__genmod
