        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:43 2018
        MODULE VTX2CTR__genmod
          INTERFACE 
            SUBROUTINE VTX2CTR(VARRAY,CARRAY)
              USE GEOMETRY
              REAL(KIND=8), INTENT(IN) :: VARRAY(N_PTS)
              REAL(KIND=8), INTENT(OUT) :: CARRAY(N_ELEMS)
            END SUBROUTINE VTX2CTR
          END INTERFACE 
        END MODULE VTX2CTR__genmod
