        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:50 2018
        MODULE WENSLP_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WENSLP_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP_FLUXES
          END INTERFACE 
        END MODULE WENSLP_FLUXES__genmod
