        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:58 2018
        MODULE WENSLP3_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WENSLP3_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP3_FLUXES
          END INTERFACE 
        END MODULE WENSLP3_FLUXES__genmod
