        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:15 2018
        MODULE WENSLP2_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WENSLP2_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WENSLP2_FLUXES
          END INTERFACE 
        END MODULE WENSLP2_FLUXES__genmod
