        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:43 2018
        MODULE WESLP_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WESLP_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP_FLUXES
          END INTERFACE 
        END MODULE WESLP_FLUXES__genmod
