        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:23 2018
        MODULE WESLP3_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WESLP3_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP3_FLUXES
          END INTERFACE 
        END MODULE WESLP3_FLUXES__genmod
