        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:15 2018
        MODULE WESLP2_FLUXES__genmod
          INTERFACE 
            SUBROUTINE WESLP2_FLUXES(HDRY)
              REAL(KIND=8), INTENT(IN) :: HDRY
            END SUBROUTINE WESLP2_FLUXES
          END INTERFACE 
        END MODULE WESLP2_FLUXES__genmod
