        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:53 2018
        MODULE WRITE_CGNS_CELL__genmod
          INTERFACE 
            SUBROUTINE WRITE_CGNS_CELL(TTIME)
              REAL(KIND=8), INTENT(IN) :: TTIME
            END SUBROUTINE WRITE_CGNS_CELL
          END INTERFACE 
        END MODULE WRITE_CGNS_CELL__genmod
