        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 15:00:19 2018
        MODULE WRITE_CGNS__genmod
          INTERFACE 
            SUBROUTINE WRITE_CGNS(TTIME)
              REAL(KIND=8), INTENT(IN) :: TTIME
            END SUBROUTINE WRITE_CGNS
          END INTERFACE 
        END MODULE WRITE_CGNS__genmod
