        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 19 14:12:20 2018
        MODULE ZETA_BCS__genmod
          INTERFACE 
            SUBROUTINE ZETA_BCS
            END SUBROUTINE ZETA_BCS
          END INTERFACE 
        END MODULE ZETA_BCS__genmod
